// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_script.proto

package rbk.protocol;

public final class MessageScript {
  private MessageScript() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Message_ScriptStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rbk.protocol.Message_ScriptStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.rbk.protocol.Message_ScriptStatus.Status status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.rbk.protocol.Message_ScriptStatus.Status status = 1;</code>
     * @return The status.
     */
    rbk.protocol.MessageScript.Message_ScriptStatus.Status getStatus();

    /**
     * <code>string res = 2;</code>
     * @return The res.
     */
    java.lang.String getRes();
    /**
     * <code>string res = 2;</code>
     * @return The bytes for res.
     */
    com.google.protobuf.ByteString
        getResBytes();
  }
  /**
   * Protobuf type {@code rbk.protocol.Message_ScriptStatus}
   */
  public static final class Message_ScriptStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rbk.protocol.Message_ScriptStatus)
      Message_ScriptStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message_ScriptStatus.newBuilder() to construct.
    private Message_ScriptStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message_ScriptStatus() {
      status_ = 0;
      res_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message_ScriptStatus();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rbk.protocol.MessageScript.internal_static_rbk_protocol_Message_ScriptStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rbk.protocol.MessageScript.internal_static_rbk_protocol_Message_ScriptStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rbk.protocol.MessageScript.Message_ScriptStatus.class, rbk.protocol.MessageScript.Message_ScriptStatus.Builder.class);
    }

    /**
     * Protobuf enum {@code rbk.protocol.Message_ScriptStatus.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>StatusNone = 0;</code>
       */
      StatusNone(0),
      /**
       * <code>Waiting = 1;</code>
       */
      Waiting(1),
      /**
       * <code>Running = 2;</code>
       */
      Running(2),
      /**
       * <code>Suspended = 3;</code>
       */
      Suspended(3),
      /**
       * <code>Completed = 4;</code>
       */
      Completed(4),
      /**
       * <code>Failed = 5;</code>
       */
      Failed(5),
      /**
       * <code>Canceled = 6;</code>
       */
      Canceled(6),
      /**
       * <code>OverTime = 7;</code>
       */
      OverTime(7),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>StatusNone = 0;</code>
       */
      public static final int StatusNone_VALUE = 0;
      /**
       * <code>Waiting = 1;</code>
       */
      public static final int Waiting_VALUE = 1;
      /**
       * <code>Running = 2;</code>
       */
      public static final int Running_VALUE = 2;
      /**
       * <code>Suspended = 3;</code>
       */
      public static final int Suspended_VALUE = 3;
      /**
       * <code>Completed = 4;</code>
       */
      public static final int Completed_VALUE = 4;
      /**
       * <code>Failed = 5;</code>
       */
      public static final int Failed_VALUE = 5;
      /**
       * <code>Canceled = 6;</code>
       */
      public static final int Canceled_VALUE = 6;
      /**
       * <code>OverTime = 7;</code>
       */
      public static final int OverTime_VALUE = 7;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Status forNumber(int value) {
        switch (value) {
          case 0: return StatusNone;
          case 1: return Waiting;
          case 2: return Running;
          case 3: return Suspended;
          case 4: return Completed;
          case 5: return Failed;
          case 6: return Canceled;
          case 7: return OverTime;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return rbk.protocol.MessageScript.Message_ScriptStatus.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:rbk.protocol.Message_ScriptStatus.Status)
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_ = 0;
    /**
     * <code>.rbk.protocol.Message_ScriptStatus.Status status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.rbk.protocol.Message_ScriptStatus.Status status = 1;</code>
     * @return The status.
     */
    @java.lang.Override public rbk.protocol.MessageScript.Message_ScriptStatus.Status getStatus() {
      rbk.protocol.MessageScript.Message_ScriptStatus.Status result = rbk.protocol.MessageScript.Message_ScriptStatus.Status.forNumber(status_);
      return result == null ? rbk.protocol.MessageScript.Message_ScriptStatus.Status.UNRECOGNIZED : result;
    }

    public static final int RES_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object res_ = "";
    /**
     * <code>string res = 2;</code>
     * @return The res.
     */
    @java.lang.Override
    public java.lang.String getRes() {
      java.lang.Object ref = res_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        res_ = s;
        return s;
      }
    }
    /**
     * <code>string res = 2;</code>
     * @return The bytes for res.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResBytes() {
      java.lang.Object ref = res_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        res_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != rbk.protocol.MessageScript.Message_ScriptStatus.Status.StatusNone.getNumber()) {
        output.writeEnum(1, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(res_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, res_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != rbk.protocol.MessageScript.Message_ScriptStatus.Status.StatusNone.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(res_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, res_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rbk.protocol.MessageScript.Message_ScriptStatus)) {
        return super.equals(obj);
      }
      rbk.protocol.MessageScript.Message_ScriptStatus other = (rbk.protocol.MessageScript.Message_ScriptStatus) obj;

      if (status_ != other.status_) return false;
      if (!getRes()
          .equals(other.getRes())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + RES_FIELD_NUMBER;
      hash = (53 * hash) + getRes().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rbk.protocol.MessageScript.Message_ScriptStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageScript.Message_ScriptStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageScript.Message_ScriptStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageScript.Message_ScriptStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageScript.Message_ScriptStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageScript.Message_ScriptStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageScript.Message_ScriptStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.MessageScript.Message_ScriptStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static rbk.protocol.MessageScript.Message_ScriptStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static rbk.protocol.MessageScript.Message_ScriptStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rbk.protocol.MessageScript.Message_ScriptStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.MessageScript.Message_ScriptStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rbk.protocol.MessageScript.Message_ScriptStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rbk.protocol.Message_ScriptStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rbk.protocol.Message_ScriptStatus)
        rbk.protocol.MessageScript.Message_ScriptStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rbk.protocol.MessageScript.internal_static_rbk_protocol_Message_ScriptStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rbk.protocol.MessageScript.internal_static_rbk_protocol_Message_ScriptStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rbk.protocol.MessageScript.Message_ScriptStatus.class, rbk.protocol.MessageScript.Message_ScriptStatus.Builder.class);
      }

      // Construct using rbk.protocol.MessageScript.Message_ScriptStatus.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        status_ = 0;
        res_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rbk.protocol.MessageScript.internal_static_rbk_protocol_Message_ScriptStatus_descriptor;
      }

      @java.lang.Override
      public rbk.protocol.MessageScript.Message_ScriptStatus getDefaultInstanceForType() {
        return rbk.protocol.MessageScript.Message_ScriptStatus.getDefaultInstance();
      }

      @java.lang.Override
      public rbk.protocol.MessageScript.Message_ScriptStatus build() {
        rbk.protocol.MessageScript.Message_ScriptStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rbk.protocol.MessageScript.Message_ScriptStatus buildPartial() {
        rbk.protocol.MessageScript.Message_ScriptStatus result = new rbk.protocol.MessageScript.Message_ScriptStatus(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(rbk.protocol.MessageScript.Message_ScriptStatus result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.res_ = res_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rbk.protocol.MessageScript.Message_ScriptStatus) {
          return mergeFrom((rbk.protocol.MessageScript.Message_ScriptStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rbk.protocol.MessageScript.Message_ScriptStatus other) {
        if (other == rbk.protocol.MessageScript.Message_ScriptStatus.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getRes().isEmpty()) {
          res_ = other.res_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                status_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                res_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int status_ = 0;
      /**
       * <code>.rbk.protocol.Message_ScriptStatus.Status status = 1;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.rbk.protocol.Message_ScriptStatus.Status status = 1;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.rbk.protocol.Message_ScriptStatus.Status status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public rbk.protocol.MessageScript.Message_ScriptStatus.Status getStatus() {
        rbk.protocol.MessageScript.Message_ScriptStatus.Status result = rbk.protocol.MessageScript.Message_ScriptStatus.Status.forNumber(status_);
        return result == null ? rbk.protocol.MessageScript.Message_ScriptStatus.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.rbk.protocol.Message_ScriptStatus.Status status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(rbk.protocol.MessageScript.Message_ScriptStatus.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.rbk.protocol.Message_ScriptStatus.Status status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object res_ = "";
      /**
       * <code>string res = 2;</code>
       * @return The res.
       */
      public java.lang.String getRes() {
        java.lang.Object ref = res_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          res_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string res = 2;</code>
       * @return The bytes for res.
       */
      public com.google.protobuf.ByteString
          getResBytes() {
        java.lang.Object ref = res_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          res_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string res = 2;</code>
       * @param value The res to set.
       * @return This builder for chaining.
       */
      public Builder setRes(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        res_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string res = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRes() {
        res_ = getDefaultInstance().getRes();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string res = 2;</code>
       * @param value The bytes for res to set.
       * @return This builder for chaining.
       */
      public Builder setResBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        res_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rbk.protocol.Message_ScriptStatus)
    }

    // @@protoc_insertion_point(class_scope:rbk.protocol.Message_ScriptStatus)
    private static final rbk.protocol.MessageScript.Message_ScriptStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rbk.protocol.MessageScript.Message_ScriptStatus();
    }

    public static rbk.protocol.MessageScript.Message_ScriptStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message_ScriptStatus>
        PARSER = new com.google.protobuf.AbstractParser<Message_ScriptStatus>() {
      @java.lang.Override
      public Message_ScriptStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message_ScriptStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message_ScriptStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rbk.protocol.MessageScript.Message_ScriptStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rbk_protocol_Message_ScriptStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rbk_protocol_Message_ScriptStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024message_script.proto\022\014rbk.protocol\"\330\001\n" +
      "\024Message_ScriptStatus\0229\n\006status\030\001 \001(\0162)." +
      "rbk.protocol.Message_ScriptStatus.Status" +
      "\022\013\n\003res\030\002 \001(\t\"x\n\006Status\022\016\n\nStatusNone\020\000\022" +
      "\013\n\007Waiting\020\001\022\013\n\007Running\020\002\022\r\n\tSuspended\020\003" +
      "\022\r\n\tCompleted\020\004\022\n\n\006Failed\020\005\022\014\n\010Canceled\020" +
      "\006\022\014\n\010OverTime\020\007b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rbk_protocol_Message_ScriptStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rbk_protocol_Message_ScriptStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rbk_protocol_Message_ScriptStatus_descriptor,
        new java.lang.String[] { "Status", "Res", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
