// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_tts.proto

package rbk.protocol;

public final class MessageTts {
  private MessageTts() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Message_TTSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rbk.protocol.Message_TTS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string str = 1;</code>
     * @return The str.
     */
    java.lang.String getStr();
    /**
     * <code>string str = 1;</code>
     * @return The bytes for str.
     */
    com.google.protobuf.ByteString
        getStrBytes();

    /**
     * <code>bool is_setting = 2;</code>
     * @return The isSetting.
     */
    boolean getIsSetting();

    /**
     * <code>int32 voiceId = 3;</code>
     * @return The voiceId.
     */
    int getVoiceId();

    /**
     * <code>int32 speed = 4;</code>
     * @return The speed.
     */
    int getSpeed();

    /**
     * <code>int32 volumn = 5;</code>
     * @return The volumn.
     */
    int getVolumn();
  }
  /**
   * Protobuf type {@code rbk.protocol.Message_TTS}
   */
  public static final class Message_TTS extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rbk.protocol.Message_TTS)
      Message_TTSOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message_TTS.newBuilder() to construct.
    private Message_TTS(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message_TTS() {
      str_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message_TTS();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rbk.protocol.MessageTts.internal_static_rbk_protocol_Message_TTS_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rbk.protocol.MessageTts.internal_static_rbk_protocol_Message_TTS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rbk.protocol.MessageTts.Message_TTS.class, rbk.protocol.MessageTts.Message_TTS.Builder.class);
    }

    public static final int STR_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object str_ = "";
    /**
     * <code>string str = 1;</code>
     * @return The str.
     */
    @java.lang.Override
    public java.lang.String getStr() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str_ = s;
        return s;
      }
    }
    /**
     * <code>string str = 1;</code>
     * @return The bytes for str.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStrBytes() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_SETTING_FIELD_NUMBER = 2;
    private boolean isSetting_ = false;
    /**
     * <code>bool is_setting = 2;</code>
     * @return The isSetting.
     */
    @java.lang.Override
    public boolean getIsSetting() {
      return isSetting_;
    }

    public static final int VOICEID_FIELD_NUMBER = 3;
    private int voiceId_ = 0;
    /**
     * <code>int32 voiceId = 3;</code>
     * @return The voiceId.
     */
    @java.lang.Override
    public int getVoiceId() {
      return voiceId_;
    }

    public static final int SPEED_FIELD_NUMBER = 4;
    private int speed_ = 0;
    /**
     * <code>int32 speed = 4;</code>
     * @return The speed.
     */
    @java.lang.Override
    public int getSpeed() {
      return speed_;
    }

    public static final int VOLUMN_FIELD_NUMBER = 5;
    private int volumn_ = 0;
    /**
     * <code>int32 volumn = 5;</code>
     * @return The volumn.
     */
    @java.lang.Override
    public int getVolumn() {
      return volumn_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(str_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, str_);
      }
      if (isSetting_ != false) {
        output.writeBool(2, isSetting_);
      }
      if (voiceId_ != 0) {
        output.writeInt32(3, voiceId_);
      }
      if (speed_ != 0) {
        output.writeInt32(4, speed_);
      }
      if (volumn_ != 0) {
        output.writeInt32(5, volumn_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(str_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, str_);
      }
      if (isSetting_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isSetting_);
      }
      if (voiceId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, voiceId_);
      }
      if (speed_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, speed_);
      }
      if (volumn_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, volumn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rbk.protocol.MessageTts.Message_TTS)) {
        return super.equals(obj);
      }
      rbk.protocol.MessageTts.Message_TTS other = (rbk.protocol.MessageTts.Message_TTS) obj;

      if (!getStr()
          .equals(other.getStr())) return false;
      if (getIsSetting()
          != other.getIsSetting()) return false;
      if (getVoiceId()
          != other.getVoiceId()) return false;
      if (getSpeed()
          != other.getSpeed()) return false;
      if (getVolumn()
          != other.getVolumn()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STR_FIELD_NUMBER;
      hash = (53 * hash) + getStr().hashCode();
      hash = (37 * hash) + IS_SETTING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSetting());
      hash = (37 * hash) + VOICEID_FIELD_NUMBER;
      hash = (53 * hash) + getVoiceId();
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + getSpeed();
      hash = (37 * hash) + VOLUMN_FIELD_NUMBER;
      hash = (53 * hash) + getVolumn();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rbk.protocol.MessageTts.Message_TTS parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageTts.Message_TTS parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageTts.Message_TTS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageTts.Message_TTS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageTts.Message_TTS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageTts.Message_TTS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageTts.Message_TTS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.MessageTts.Message_TTS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static rbk.protocol.MessageTts.Message_TTS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static rbk.protocol.MessageTts.Message_TTS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rbk.protocol.MessageTts.Message_TTS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.MessageTts.Message_TTS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rbk.protocol.MessageTts.Message_TTS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rbk.protocol.Message_TTS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rbk.protocol.Message_TTS)
        rbk.protocol.MessageTts.Message_TTSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rbk.protocol.MessageTts.internal_static_rbk_protocol_Message_TTS_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rbk.protocol.MessageTts.internal_static_rbk_protocol_Message_TTS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rbk.protocol.MessageTts.Message_TTS.class, rbk.protocol.MessageTts.Message_TTS.Builder.class);
      }

      // Construct using rbk.protocol.MessageTts.Message_TTS.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        str_ = "";
        isSetting_ = false;
        voiceId_ = 0;
        speed_ = 0;
        volumn_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rbk.protocol.MessageTts.internal_static_rbk_protocol_Message_TTS_descriptor;
      }

      @java.lang.Override
      public rbk.protocol.MessageTts.Message_TTS getDefaultInstanceForType() {
        return rbk.protocol.MessageTts.Message_TTS.getDefaultInstance();
      }

      @java.lang.Override
      public rbk.protocol.MessageTts.Message_TTS build() {
        rbk.protocol.MessageTts.Message_TTS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rbk.protocol.MessageTts.Message_TTS buildPartial() {
        rbk.protocol.MessageTts.Message_TTS result = new rbk.protocol.MessageTts.Message_TTS(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(rbk.protocol.MessageTts.Message_TTS result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.str_ = str_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.isSetting_ = isSetting_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.voiceId_ = voiceId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.speed_ = speed_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.volumn_ = volumn_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rbk.protocol.MessageTts.Message_TTS) {
          return mergeFrom((rbk.protocol.MessageTts.Message_TTS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rbk.protocol.MessageTts.Message_TTS other) {
        if (other == rbk.protocol.MessageTts.Message_TTS.getDefaultInstance()) return this;
        if (!other.getStr().isEmpty()) {
          str_ = other.str_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getIsSetting() != false) {
          setIsSetting(other.getIsSetting());
        }
        if (other.getVoiceId() != 0) {
          setVoiceId(other.getVoiceId());
        }
        if (other.getSpeed() != 0) {
          setSpeed(other.getSpeed());
        }
        if (other.getVolumn() != 0) {
          setVolumn(other.getVolumn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                str_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                isSetting_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                voiceId_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                speed_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                volumn_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object str_ = "";
      /**
       * <code>string str = 1;</code>
       * @return The str.
       */
      public java.lang.String getStr() {
        java.lang.Object ref = str_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          str_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string str = 1;</code>
       * @return The bytes for str.
       */
      public com.google.protobuf.ByteString
          getStrBytes() {
        java.lang.Object ref = str_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string str = 1;</code>
       * @param value The str to set.
       * @return This builder for chaining.
       */
      public Builder setStr(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        str_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string str = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStr() {
        str_ = getDefaultInstance().getStr();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string str = 1;</code>
       * @param value The bytes for str to set.
       * @return This builder for chaining.
       */
      public Builder setStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        str_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private boolean isSetting_ ;
      /**
       * <code>bool is_setting = 2;</code>
       * @return The isSetting.
       */
      @java.lang.Override
      public boolean getIsSetting() {
        return isSetting_;
      }
      /**
       * <code>bool is_setting = 2;</code>
       * @param value The isSetting to set.
       * @return This builder for chaining.
       */
      public Builder setIsSetting(boolean value) {

        isSetting_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_setting = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsSetting() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isSetting_ = false;
        onChanged();
        return this;
      }

      private int voiceId_ ;
      /**
       * <code>int32 voiceId = 3;</code>
       * @return The voiceId.
       */
      @java.lang.Override
      public int getVoiceId() {
        return voiceId_;
      }
      /**
       * <code>int32 voiceId = 3;</code>
       * @param value The voiceId to set.
       * @return This builder for chaining.
       */
      public Builder setVoiceId(int value) {

        voiceId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 voiceId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoiceId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        voiceId_ = 0;
        onChanged();
        return this;
      }

      private int speed_ ;
      /**
       * <code>int32 speed = 4;</code>
       * @return The speed.
       */
      @java.lang.Override
      public int getSpeed() {
        return speed_;
      }
      /**
       * <code>int32 speed = 4;</code>
       * @param value The speed to set.
       * @return This builder for chaining.
       */
      public Builder setSpeed(int value) {

        speed_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 speed = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        speed_ = 0;
        onChanged();
        return this;
      }

      private int volumn_ ;
      /**
       * <code>int32 volumn = 5;</code>
       * @return The volumn.
       */
      @java.lang.Override
      public int getVolumn() {
        return volumn_;
      }
      /**
       * <code>int32 volumn = 5;</code>
       * @param value The volumn to set.
       * @return This builder for chaining.
       */
      public Builder setVolumn(int value) {

        volumn_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 volumn = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearVolumn() {
        bitField0_ = (bitField0_ & ~0x00000010);
        volumn_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rbk.protocol.Message_TTS)
    }

    // @@protoc_insertion_point(class_scope:rbk.protocol.Message_TTS)
    private static final rbk.protocol.MessageTts.Message_TTS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rbk.protocol.MessageTts.Message_TTS();
    }

    public static rbk.protocol.MessageTts.Message_TTS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message_TTS>
        PARSER = new com.google.protobuf.AbstractParser<Message_TTS>() {
      @java.lang.Override
      public Message_TTS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message_TTS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message_TTS> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rbk.protocol.MessageTts.Message_TTS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rbk_protocol_Message_TTS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rbk_protocol_Message_TTS_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021message_tts.proto\022\014rbk.protocol\"^\n\013Mes" +
      "sage_TTS\022\013\n\003str\030\001 \001(\t\022\022\n\nis_setting\030\002 \001(" +
      "\010\022\017\n\007voiceId\030\003 \001(\005\022\r\n\005speed\030\004 \001(\005\022\016\n\006vol" +
      "umn\030\005 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rbk_protocol_Message_TTS_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rbk_protocol_Message_TTS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rbk_protocol_Message_TTS_descriptor,
        new java.lang.String[] { "Str", "IsSetting", "VoiceId", "Speed", "Volumn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
