// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_hook.proto

package rbk.protocol;

public final class MessageHook {
  private MessageHook() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Message_HookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rbk.protocol.Message_Hook)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool mode = 1;</code>
     * @return The mode.
     */
    boolean getMode();

    /**
     * <code>uint32 state = 2;</code>
     * @return The state.
     */
    int getState();

    /**
     * <code>bool enable = 3;</code>
     * @return The enable.
     */
    boolean getEnable();

    /**
     * <code>uint32 errorCode = 4;</code>
     * @return The errorCode.
     */
    int getErrorCode();

    /**
     * <code>uint32 angle = 5;</code>
     * @return The angle.
     */
    int getAngle();

    /**
     * <code>uint32 height = 6;</code>
     * @return The height.
     */
    int getHeight();

    /**
     * <code>bool clampingState = 7;</code>
     * @return The clampingState.
     */
    boolean getClampingState();

    /**
     * <code>bool isFull = 8;</code>
     * @return The isFull.
     */
    boolean getIsFull();

    /**
     * <code>bool emc = 9;</code>
     * @return The emc.
     */
    boolean getEmc();
  }
  /**
   * Protobuf type {@code rbk.protocol.Message_Hook}
   */
  public static final class Message_Hook extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rbk.protocol.Message_Hook)
      Message_HookOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message_Hook.newBuilder() to construct.
    private Message_Hook(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message_Hook() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message_Hook();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rbk.protocol.MessageHook.internal_static_rbk_protocol_Message_Hook_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rbk.protocol.MessageHook.internal_static_rbk_protocol_Message_Hook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rbk.protocol.MessageHook.Message_Hook.class, rbk.protocol.MessageHook.Message_Hook.Builder.class);
    }

    public static final int MODE_FIELD_NUMBER = 1;
    private boolean mode_ = false;
    /**
     * <code>bool mode = 1;</code>
     * @return The mode.
     */
    @java.lang.Override
    public boolean getMode() {
      return mode_;
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private int state_ = 0;
    /**
     * <code>uint32 state = 2;</code>
     * @return The state.
     */
    @java.lang.Override
    public int getState() {
      return state_;
    }

    public static final int ENABLE_FIELD_NUMBER = 3;
    private boolean enable_ = false;
    /**
     * <code>bool enable = 3;</code>
     * @return The enable.
     */
    @java.lang.Override
    public boolean getEnable() {
      return enable_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 4;
    private int errorCode_ = 0;
    /**
     * <code>uint32 errorCode = 4;</code>
     * @return The errorCode.
     */
    @java.lang.Override
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int ANGLE_FIELD_NUMBER = 5;
    private int angle_ = 0;
    /**
     * <code>uint32 angle = 5;</code>
     * @return The angle.
     */
    @java.lang.Override
    public int getAngle() {
      return angle_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 6;
    private int height_ = 0;
    /**
     * <code>uint32 height = 6;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }

    public static final int CLAMPINGSTATE_FIELD_NUMBER = 7;
    private boolean clampingState_ = false;
    /**
     * <code>bool clampingState = 7;</code>
     * @return The clampingState.
     */
    @java.lang.Override
    public boolean getClampingState() {
      return clampingState_;
    }

    public static final int ISFULL_FIELD_NUMBER = 8;
    private boolean isFull_ = false;
    /**
     * <code>bool isFull = 8;</code>
     * @return The isFull.
     */
    @java.lang.Override
    public boolean getIsFull() {
      return isFull_;
    }

    public static final int EMC_FIELD_NUMBER = 9;
    private boolean emc_ = false;
    /**
     * <code>bool emc = 9;</code>
     * @return The emc.
     */
    @java.lang.Override
    public boolean getEmc() {
      return emc_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mode_ != false) {
        output.writeBool(1, mode_);
      }
      if (state_ != 0) {
        output.writeUInt32(2, state_);
      }
      if (enable_ != false) {
        output.writeBool(3, enable_);
      }
      if (errorCode_ != 0) {
        output.writeUInt32(4, errorCode_);
      }
      if (angle_ != 0) {
        output.writeUInt32(5, angle_);
      }
      if (height_ != 0) {
        output.writeUInt32(6, height_);
      }
      if (clampingState_ != false) {
        output.writeBool(7, clampingState_);
      }
      if (isFull_ != false) {
        output.writeBool(8, isFull_);
      }
      if (emc_ != false) {
        output.writeBool(9, emc_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mode_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, mode_);
      }
      if (state_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, state_);
      }
      if (enable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, enable_);
      }
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, errorCode_);
      }
      if (angle_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, angle_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, height_);
      }
      if (clampingState_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, clampingState_);
      }
      if (isFull_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, isFull_);
      }
      if (emc_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, emc_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rbk.protocol.MessageHook.Message_Hook)) {
        return super.equals(obj);
      }
      rbk.protocol.MessageHook.Message_Hook other = (rbk.protocol.MessageHook.Message_Hook) obj;

      if (getMode()
          != other.getMode()) return false;
      if (getState()
          != other.getState()) return false;
      if (getEnable()
          != other.getEnable()) return false;
      if (getErrorCode()
          != other.getErrorCode()) return false;
      if (getAngle()
          != other.getAngle()) return false;
      if (getHeight()
          != other.getHeight()) return false;
      if (getClampingState()
          != other.getClampingState()) return false;
      if (getIsFull()
          != other.getIsFull()) return false;
      if (getEmc()
          != other.getEmc()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MODE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMode());
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState();
      hash = (37 * hash) + ENABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEnable());
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (37 * hash) + ANGLE_FIELD_NUMBER;
      hash = (53 * hash) + getAngle();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (37 * hash) + CLAMPINGSTATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getClampingState());
      hash = (37 * hash) + ISFULL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFull());
      hash = (37 * hash) + EMC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEmc());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rbk.protocol.MessageHook.Message_Hook parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageHook.Message_Hook parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageHook.Message_Hook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageHook.Message_Hook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageHook.Message_Hook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageHook.Message_Hook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageHook.Message_Hook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.MessageHook.Message_Hook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static rbk.protocol.MessageHook.Message_Hook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static rbk.protocol.MessageHook.Message_Hook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rbk.protocol.MessageHook.Message_Hook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.MessageHook.Message_Hook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rbk.protocol.MessageHook.Message_Hook prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rbk.protocol.Message_Hook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rbk.protocol.Message_Hook)
        rbk.protocol.MessageHook.Message_HookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rbk.protocol.MessageHook.internal_static_rbk_protocol_Message_Hook_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rbk.protocol.MessageHook.internal_static_rbk_protocol_Message_Hook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rbk.protocol.MessageHook.Message_Hook.class, rbk.protocol.MessageHook.Message_Hook.Builder.class);
      }

      // Construct using rbk.protocol.MessageHook.Message_Hook.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        mode_ = false;
        state_ = 0;
        enable_ = false;
        errorCode_ = 0;
        angle_ = 0;
        height_ = 0;
        clampingState_ = false;
        isFull_ = false;
        emc_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rbk.protocol.MessageHook.internal_static_rbk_protocol_Message_Hook_descriptor;
      }

      @java.lang.Override
      public rbk.protocol.MessageHook.Message_Hook getDefaultInstanceForType() {
        return rbk.protocol.MessageHook.Message_Hook.getDefaultInstance();
      }

      @java.lang.Override
      public rbk.protocol.MessageHook.Message_Hook build() {
        rbk.protocol.MessageHook.Message_Hook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rbk.protocol.MessageHook.Message_Hook buildPartial() {
        rbk.protocol.MessageHook.Message_Hook result = new rbk.protocol.MessageHook.Message_Hook(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(rbk.protocol.MessageHook.Message_Hook result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.mode_ = mode_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.state_ = state_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.enable_ = enable_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.errorCode_ = errorCode_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.angle_ = angle_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.height_ = height_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.clampingState_ = clampingState_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.isFull_ = isFull_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.emc_ = emc_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rbk.protocol.MessageHook.Message_Hook) {
          return mergeFrom((rbk.protocol.MessageHook.Message_Hook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rbk.protocol.MessageHook.Message_Hook other) {
        if (other == rbk.protocol.MessageHook.Message_Hook.getDefaultInstance()) return this;
        if (other.getMode() != false) {
          setMode(other.getMode());
        }
        if (other.getState() != 0) {
          setState(other.getState());
        }
        if (other.getEnable() != false) {
          setEnable(other.getEnable());
        }
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        if (other.getAngle() != 0) {
          setAngle(other.getAngle());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        if (other.getClampingState() != false) {
          setClampingState(other.getClampingState());
        }
        if (other.getIsFull() != false) {
          setIsFull(other.getIsFull());
        }
        if (other.getEmc() != false) {
          setEmc(other.getEmc());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                mode_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                state_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                enable_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                errorCode_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                angle_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                height_ = input.readUInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                clampingState_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                isFull_ = input.readBool();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                emc_ = input.readBool();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean mode_ ;
      /**
       * <code>bool mode = 1;</code>
       * @return The mode.
       */
      @java.lang.Override
      public boolean getMode() {
        return mode_;
      }
      /**
       * <code>bool mode = 1;</code>
       * @param value The mode to set.
       * @return This builder for chaining.
       */
      public Builder setMode(boolean value) {

        mode_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool mode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mode_ = false;
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <code>uint32 state = 2;</code>
       * @return The state.
       */
      @java.lang.Override
      public int getState() {
        return state_;
      }
      /**
       * <code>uint32 state = 2;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(int value) {

        state_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 state = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = 0;
        onChanged();
        return this;
      }

      private boolean enable_ ;
      /**
       * <code>bool enable = 3;</code>
       * @return The enable.
       */
      @java.lang.Override
      public boolean getEnable() {
        return enable_;
      }
      /**
       * <code>bool enable = 3;</code>
       * @param value The enable to set.
       * @return This builder for chaining.
       */
      public Builder setEnable(boolean value) {

        enable_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool enable = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnable() {
        bitField0_ = (bitField0_ & ~0x00000004);
        enable_ = false;
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>uint32 errorCode = 4;</code>
       * @return The errorCode.
       */
      @java.lang.Override
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>uint32 errorCode = 4;</code>
       * @param value The errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCode(int value) {

        errorCode_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 errorCode = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private int angle_ ;
      /**
       * <code>uint32 angle = 5;</code>
       * @return The angle.
       */
      @java.lang.Override
      public int getAngle() {
        return angle_;
      }
      /**
       * <code>uint32 angle = 5;</code>
       * @param value The angle to set.
       * @return This builder for chaining.
       */
      public Builder setAngle(int value) {

        angle_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 angle = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAngle() {
        bitField0_ = (bitField0_ & ~0x00000010);
        angle_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>uint32 height = 6;</code>
       * @return The height.
       */
      @java.lang.Override
      public int getHeight() {
        return height_;
      }
      /**
       * <code>uint32 height = 6;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {

        height_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 height = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000020);
        height_ = 0;
        onChanged();
        return this;
      }

      private boolean clampingState_ ;
      /**
       * <code>bool clampingState = 7;</code>
       * @return The clampingState.
       */
      @java.lang.Override
      public boolean getClampingState() {
        return clampingState_;
      }
      /**
       * <code>bool clampingState = 7;</code>
       * @param value The clampingState to set.
       * @return This builder for chaining.
       */
      public Builder setClampingState(boolean value) {

        clampingState_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>bool clampingState = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearClampingState() {
        bitField0_ = (bitField0_ & ~0x00000040);
        clampingState_ = false;
        onChanged();
        return this;
      }

      private boolean isFull_ ;
      /**
       * <code>bool isFull = 8;</code>
       * @return The isFull.
       */
      @java.lang.Override
      public boolean getIsFull() {
        return isFull_;
      }
      /**
       * <code>bool isFull = 8;</code>
       * @param value The isFull to set.
       * @return This builder for chaining.
       */
      public Builder setIsFull(boolean value) {

        isFull_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>bool isFull = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsFull() {
        bitField0_ = (bitField0_ & ~0x00000080);
        isFull_ = false;
        onChanged();
        return this;
      }

      private boolean emc_ ;
      /**
       * <code>bool emc = 9;</code>
       * @return The emc.
       */
      @java.lang.Override
      public boolean getEmc() {
        return emc_;
      }
      /**
       * <code>bool emc = 9;</code>
       * @param value The emc to set.
       * @return This builder for chaining.
       */
      public Builder setEmc(boolean value) {

        emc_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>bool emc = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmc() {
        bitField0_ = (bitField0_ & ~0x00000100);
        emc_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rbk.protocol.Message_Hook)
    }

    // @@protoc_insertion_point(class_scope:rbk.protocol.Message_Hook)
    private static final rbk.protocol.MessageHook.Message_Hook DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rbk.protocol.MessageHook.Message_Hook();
    }

    public static rbk.protocol.MessageHook.Message_Hook getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message_Hook>
        PARSER = new com.google.protobuf.AbstractParser<Message_Hook>() {
      @java.lang.Override
      public Message_Hook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message_Hook> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message_Hook> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rbk.protocol.MessageHook.Message_Hook getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rbk_protocol_Message_Hook_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rbk_protocol_Message_Hook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022message_hook.proto\022\014rbk.protocol\"\241\001\n\014M" +
      "essage_Hook\022\014\n\004mode\030\001 \001(\010\022\r\n\005state\030\002 \001(\r" +
      "\022\016\n\006enable\030\003 \001(\010\022\021\n\terrorCode\030\004 \001(\r\022\r\n\005a" +
      "ngle\030\005 \001(\r\022\016\n\006height\030\006 \001(\r\022\025\n\rclampingSt" +
      "ate\030\007 \001(\010\022\016\n\006isFull\030\010 \001(\010\022\013\n\003emc\030\t \001(\010b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rbk_protocol_Message_Hook_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rbk_protocol_Message_Hook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rbk_protocol_Message_Hook_descriptor,
        new java.lang.String[] { "Mode", "State", "Enable", "ErrorCode", "Angle", "Height", "ClampingState", "IsFull", "Emc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
