// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_tracking.proto

package rbk.protocol;

public final class MessageTracking {
  private MessageTracking() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Message_TrackingStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rbk.protocol.Message_TrackingStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double x = 1;</code>
     * @return The x.
     */
    double getX();

    /**
     * <code>double y = 2;</code>
     * @return The y.
     */
    double getY();

    /**
     * <code>.rbk.protocol.Message_TrackingStatus.TrackingStatus tracking_status = 3;</code>
     * @return The enum numeric value on the wire for trackingStatus.
     */
    int getTrackingStatusValue();
    /**
     * <code>.rbk.protocol.Message_TrackingStatus.TrackingStatus tracking_status = 3;</code>
     * @return The trackingStatus.
     */
    rbk.protocol.MessageTracking.Message_TrackingStatus.TrackingStatus getTrackingStatus();
  }
  /**
   * Protobuf type {@code rbk.protocol.Message_TrackingStatus}
   */
  public static final class Message_TrackingStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rbk.protocol.Message_TrackingStatus)
      Message_TrackingStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message_TrackingStatus.newBuilder() to construct.
    private Message_TrackingStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message_TrackingStatus() {
      trackingStatus_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message_TrackingStatus();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rbk.protocol.MessageTracking.internal_static_rbk_protocol_Message_TrackingStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rbk.protocol.MessageTracking.internal_static_rbk_protocol_Message_TrackingStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rbk.protocol.MessageTracking.Message_TrackingStatus.class, rbk.protocol.MessageTracking.Message_TrackingStatus.Builder.class);
    }

    /**
     * Protobuf enum {@code rbk.protocol.Message_TrackingStatus.TrackingStatus}
     */
    public enum TrackingStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Tracking = 0;</code>
       */
      Tracking(0),
      /**
       * <code>Lose = 1;</code>
       */
      Lose(1),
      /**
       * <code>NoTarget = 2;</code>
       */
      NoTarget(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Tracking = 0;</code>
       */
      public static final int Tracking_VALUE = 0;
      /**
       * <code>Lose = 1;</code>
       */
      public static final int Lose_VALUE = 1;
      /**
       * <code>NoTarget = 2;</code>
       */
      public static final int NoTarget_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TrackingStatus valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static TrackingStatus forNumber(int value) {
        switch (value) {
          case 0: return Tracking;
          case 1: return Lose;
          case 2: return NoTarget;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TrackingStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TrackingStatus> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TrackingStatus>() {
              public TrackingStatus findValueByNumber(int number) {
                return TrackingStatus.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return rbk.protocol.MessageTracking.Message_TrackingStatus.getDescriptor().getEnumTypes().get(0);
      }

      private static final TrackingStatus[] VALUES = values();

      public static TrackingStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TrackingStatus(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:rbk.protocol.Message_TrackingStatus.TrackingStatus)
    }

    public static final int X_FIELD_NUMBER = 1;
    private double x_ = 0D;
    /**
     * <code>double x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private double y_ = 0D;
    /**
     * <code>double y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public double getY() {
      return y_;
    }

    public static final int TRACKING_STATUS_FIELD_NUMBER = 3;
    private int trackingStatus_ = 0;
    /**
     * <code>.rbk.protocol.Message_TrackingStatus.TrackingStatus tracking_status = 3;</code>
     * @return The enum numeric value on the wire for trackingStatus.
     */
    @java.lang.Override public int getTrackingStatusValue() {
      return trackingStatus_;
    }
    /**
     * <code>.rbk.protocol.Message_TrackingStatus.TrackingStatus tracking_status = 3;</code>
     * @return The trackingStatus.
     */
    @java.lang.Override public rbk.protocol.MessageTracking.Message_TrackingStatus.TrackingStatus getTrackingStatus() {
      rbk.protocol.MessageTracking.Message_TrackingStatus.TrackingStatus result = rbk.protocol.MessageTracking.Message_TrackingStatus.TrackingStatus.forNumber(trackingStatus_);
      return result == null ? rbk.protocol.MessageTracking.Message_TrackingStatus.TrackingStatus.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        output.writeDouble(1, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        output.writeDouble(2, y_);
      }
      if (trackingStatus_ != rbk.protocol.MessageTracking.Message_TrackingStatus.TrackingStatus.Tracking.getNumber()) {
        output.writeEnum(3, trackingStatus_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      if (trackingStatus_ != rbk.protocol.MessageTracking.Message_TrackingStatus.TrackingStatus.Tracking.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, trackingStatus_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rbk.protocol.MessageTracking.Message_TrackingStatus)) {
        return super.equals(obj);
      }
      rbk.protocol.MessageTracking.Message_TrackingStatus other = (rbk.protocol.MessageTracking.Message_TrackingStatus) obj;

      if (java.lang.Double.doubleToLongBits(getX())
          != java.lang.Double.doubleToLongBits(
              other.getX())) return false;
      if (java.lang.Double.doubleToLongBits(getY())
          != java.lang.Double.doubleToLongBits(
              other.getY())) return false;
      if (trackingStatus_ != other.trackingStatus_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getX()));
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getY()));
      hash = (37 * hash) + TRACKING_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + trackingStatus_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rbk.protocol.MessageTracking.Message_TrackingStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageTracking.Message_TrackingStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageTracking.Message_TrackingStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageTracking.Message_TrackingStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageTracking.Message_TrackingStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageTracking.Message_TrackingStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageTracking.Message_TrackingStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.MessageTracking.Message_TrackingStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static rbk.protocol.MessageTracking.Message_TrackingStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static rbk.protocol.MessageTracking.Message_TrackingStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rbk.protocol.MessageTracking.Message_TrackingStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.MessageTracking.Message_TrackingStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rbk.protocol.MessageTracking.Message_TrackingStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rbk.protocol.Message_TrackingStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rbk.protocol.Message_TrackingStatus)
        rbk.protocol.MessageTracking.Message_TrackingStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rbk.protocol.MessageTracking.internal_static_rbk_protocol_Message_TrackingStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rbk.protocol.MessageTracking.internal_static_rbk_protocol_Message_TrackingStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rbk.protocol.MessageTracking.Message_TrackingStatus.class, rbk.protocol.MessageTracking.Message_TrackingStatus.Builder.class);
      }

      // Construct using rbk.protocol.MessageTracking.Message_TrackingStatus.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        x_ = 0D;
        y_ = 0D;
        trackingStatus_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rbk.protocol.MessageTracking.internal_static_rbk_protocol_Message_TrackingStatus_descriptor;
      }

      @java.lang.Override
      public rbk.protocol.MessageTracking.Message_TrackingStatus getDefaultInstanceForType() {
        return rbk.protocol.MessageTracking.Message_TrackingStatus.getDefaultInstance();
      }

      @java.lang.Override
      public rbk.protocol.MessageTracking.Message_TrackingStatus build() {
        rbk.protocol.MessageTracking.Message_TrackingStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rbk.protocol.MessageTracking.Message_TrackingStatus buildPartial() {
        rbk.protocol.MessageTracking.Message_TrackingStatus result = new rbk.protocol.MessageTracking.Message_TrackingStatus(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(rbk.protocol.MessageTracking.Message_TrackingStatus result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.x_ = x_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.y_ = y_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.trackingStatus_ = trackingStatus_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rbk.protocol.MessageTracking.Message_TrackingStatus) {
          return mergeFrom((rbk.protocol.MessageTracking.Message_TrackingStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rbk.protocol.MessageTracking.Message_TrackingStatus other) {
        if (other == rbk.protocol.MessageTracking.Message_TrackingStatus.getDefaultInstance()) return this;
        if (other.getX() != 0D) {
          setX(other.getX());
        }
        if (other.getY() != 0D) {
          setY(other.getY());
        }
        if (other.trackingStatus_ != 0) {
          setTrackingStatusValue(other.getTrackingStatusValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                x_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 17: {
                y_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 24: {
                trackingStatus_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double x_ ;
      /**
       * <code>double x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public double getX() {
        return x_;
      }
      /**
       * <code>double x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(double value) {

        x_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>double y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public double getY() {
        return y_;
      }
      /**
       * <code>double y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(double value) {

        y_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        onChanged();
        return this;
      }

      private int trackingStatus_ = 0;
      /**
       * <code>.rbk.protocol.Message_TrackingStatus.TrackingStatus tracking_status = 3;</code>
       * @return The enum numeric value on the wire for trackingStatus.
       */
      @java.lang.Override public int getTrackingStatusValue() {
        return trackingStatus_;
      }
      /**
       * <code>.rbk.protocol.Message_TrackingStatus.TrackingStatus tracking_status = 3;</code>
       * @param value The enum numeric value on the wire for trackingStatus to set.
       * @return This builder for chaining.
       */
      public Builder setTrackingStatusValue(int value) {
        trackingStatus_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.rbk.protocol.Message_TrackingStatus.TrackingStatus tracking_status = 3;</code>
       * @return The trackingStatus.
       */
      @java.lang.Override
      public rbk.protocol.MessageTracking.Message_TrackingStatus.TrackingStatus getTrackingStatus() {
        rbk.protocol.MessageTracking.Message_TrackingStatus.TrackingStatus result = rbk.protocol.MessageTracking.Message_TrackingStatus.TrackingStatus.forNumber(trackingStatus_);
        return result == null ? rbk.protocol.MessageTracking.Message_TrackingStatus.TrackingStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.rbk.protocol.Message_TrackingStatus.TrackingStatus tracking_status = 3;</code>
       * @param value The trackingStatus to set.
       * @return This builder for chaining.
       */
      public Builder setTrackingStatus(rbk.protocol.MessageTracking.Message_TrackingStatus.TrackingStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        trackingStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.rbk.protocol.Message_TrackingStatus.TrackingStatus tracking_status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTrackingStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        trackingStatus_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rbk.protocol.Message_TrackingStatus)
    }

    // @@protoc_insertion_point(class_scope:rbk.protocol.Message_TrackingStatus)
    private static final rbk.protocol.MessageTracking.Message_TrackingStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rbk.protocol.MessageTracking.Message_TrackingStatus();
    }

    public static rbk.protocol.MessageTracking.Message_TrackingStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message_TrackingStatus>
        PARSER = new com.google.protobuf.AbstractParser<Message_TrackingStatus>() {
      @java.lang.Override
      public Message_TrackingStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message_TrackingStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message_TrackingStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rbk.protocol.MessageTracking.Message_TrackingStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rbk_protocol_Message_TrackingStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rbk_protocol_Message_TrackingStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026message_tracking.proto\022\014rbk.protocol\"\264" +
      "\001\n\026Message_TrackingStatus\022\t\n\001x\030\001 \001(\001\022\t\n\001" +
      "y\030\002 \001(\001\022L\n\017tracking_status\030\003 \001(\01623.rbk.p" +
      "rotocol.Message_TrackingStatus.TrackingS" +
      "tatus\"6\n\016TrackingStatus\022\014\n\010Tracking\020\000\022\010\n" +
      "\004Lose\020\001\022\014\n\010NoTarget\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rbk_protocol_Message_TrackingStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rbk_protocol_Message_TrackingStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rbk_protocol_Message_TrackingStatus_descriptor,
        new java.lang.String[] { "X", "Y", "TrackingStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
