// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_header.proto

package rbk.protocol;

public final class MessageHeader {
  private MessageHeader() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Message_HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rbk.protocol.Message_Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 pub_nsec = 1;</code>
     * @return The pubNsec.
     */
    long getPubNsec();

    /**
     * <code>uint64 data_nsec = 2;</code>
     * @return The dataNsec.
     */
    long getDataNsec();

    /**
     * <code>uint64 seq = 3;</code>
     * @return The seq.
     */
    long getSeq();

    /**
     * <code>string frame_id = 4;</code>
     * @return The frameId.
     */
    java.lang.String getFrameId();
    /**
     * <code>string frame_id = 4;</code>
     * @return The bytes for frameId.
     */
    com.google.protobuf.ByteString
        getFrameIdBytes();
  }
  /**
   * Protobuf type {@code rbk.protocol.Message_Header}
   */
  public static final class Message_Header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rbk.protocol.Message_Header)
      Message_HeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message_Header.newBuilder() to construct.
    private Message_Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message_Header() {
      frameId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message_Header();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rbk.protocol.MessageHeader.internal_static_rbk_protocol_Message_Header_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rbk.protocol.MessageHeader.internal_static_rbk_protocol_Message_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rbk.protocol.MessageHeader.Message_Header.class, rbk.protocol.MessageHeader.Message_Header.Builder.class);
    }

    public static final int PUB_NSEC_FIELD_NUMBER = 1;
    private long pubNsec_ = 0L;
    /**
     * <code>uint64 pub_nsec = 1;</code>
     * @return The pubNsec.
     */
    @java.lang.Override
    public long getPubNsec() {
      return pubNsec_;
    }

    public static final int DATA_NSEC_FIELD_NUMBER = 2;
    private long dataNsec_ = 0L;
    /**
     * <code>uint64 data_nsec = 2;</code>
     * @return The dataNsec.
     */
    @java.lang.Override
    public long getDataNsec() {
      return dataNsec_;
    }

    public static final int SEQ_FIELD_NUMBER = 3;
    private long seq_ = 0L;
    /**
     * <code>uint64 seq = 3;</code>
     * @return The seq.
     */
    @java.lang.Override
    public long getSeq() {
      return seq_;
    }

    public static final int FRAME_ID_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object frameId_ = "";
    /**
     * <code>string frame_id = 4;</code>
     * @return The frameId.
     */
    @java.lang.Override
    public java.lang.String getFrameId() {
      java.lang.Object ref = frameId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        frameId_ = s;
        return s;
      }
    }
    /**
     * <code>string frame_id = 4;</code>
     * @return The bytes for frameId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFrameIdBytes() {
      java.lang.Object ref = frameId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        frameId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pubNsec_ != 0L) {
        output.writeUInt64(1, pubNsec_);
      }
      if (dataNsec_ != 0L) {
        output.writeUInt64(2, dataNsec_);
      }
      if (seq_ != 0L) {
        output.writeUInt64(3, seq_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(frameId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, frameId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pubNsec_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, pubNsec_);
      }
      if (dataNsec_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, dataNsec_);
      }
      if (seq_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, seq_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(frameId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, frameId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rbk.protocol.MessageHeader.Message_Header)) {
        return super.equals(obj);
      }
      rbk.protocol.MessageHeader.Message_Header other = (rbk.protocol.MessageHeader.Message_Header) obj;

      if (getPubNsec()
          != other.getPubNsec()) return false;
      if (getDataNsec()
          != other.getDataNsec()) return false;
      if (getSeq()
          != other.getSeq()) return false;
      if (!getFrameId()
          .equals(other.getFrameId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PUB_NSEC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPubNsec());
      hash = (37 * hash) + DATA_NSEC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDataNsec());
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSeq());
      hash = (37 * hash) + FRAME_ID_FIELD_NUMBER;
      hash = (53 * hash) + getFrameId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rbk.protocol.MessageHeader.Message_Header parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageHeader.Message_Header parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageHeader.Message_Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageHeader.Message_Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageHeader.Message_Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageHeader.Message_Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageHeader.Message_Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.MessageHeader.Message_Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static rbk.protocol.MessageHeader.Message_Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static rbk.protocol.MessageHeader.Message_Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rbk.protocol.MessageHeader.Message_Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.MessageHeader.Message_Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rbk.protocol.MessageHeader.Message_Header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rbk.protocol.Message_Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rbk.protocol.Message_Header)
        rbk.protocol.MessageHeader.Message_HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rbk.protocol.MessageHeader.internal_static_rbk_protocol_Message_Header_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rbk.protocol.MessageHeader.internal_static_rbk_protocol_Message_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rbk.protocol.MessageHeader.Message_Header.class, rbk.protocol.MessageHeader.Message_Header.Builder.class);
      }

      // Construct using rbk.protocol.MessageHeader.Message_Header.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        pubNsec_ = 0L;
        dataNsec_ = 0L;
        seq_ = 0L;
        frameId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rbk.protocol.MessageHeader.internal_static_rbk_protocol_Message_Header_descriptor;
      }

      @java.lang.Override
      public rbk.protocol.MessageHeader.Message_Header getDefaultInstanceForType() {
        return rbk.protocol.MessageHeader.Message_Header.getDefaultInstance();
      }

      @java.lang.Override
      public rbk.protocol.MessageHeader.Message_Header build() {
        rbk.protocol.MessageHeader.Message_Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rbk.protocol.MessageHeader.Message_Header buildPartial() {
        rbk.protocol.MessageHeader.Message_Header result = new rbk.protocol.MessageHeader.Message_Header(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(rbk.protocol.MessageHeader.Message_Header result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.pubNsec_ = pubNsec_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.dataNsec_ = dataNsec_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.seq_ = seq_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.frameId_ = frameId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rbk.protocol.MessageHeader.Message_Header) {
          return mergeFrom((rbk.protocol.MessageHeader.Message_Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rbk.protocol.MessageHeader.Message_Header other) {
        if (other == rbk.protocol.MessageHeader.Message_Header.getDefaultInstance()) return this;
        if (other.getPubNsec() != 0L) {
          setPubNsec(other.getPubNsec());
        }
        if (other.getDataNsec() != 0L) {
          setDataNsec(other.getDataNsec());
        }
        if (other.getSeq() != 0L) {
          setSeq(other.getSeq());
        }
        if (!other.getFrameId().isEmpty()) {
          frameId_ = other.frameId_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                pubNsec_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                dataNsec_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                seq_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                frameId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long pubNsec_ ;
      /**
       * <code>uint64 pub_nsec = 1;</code>
       * @return The pubNsec.
       */
      @java.lang.Override
      public long getPubNsec() {
        return pubNsec_;
      }
      /**
       * <code>uint64 pub_nsec = 1;</code>
       * @param value The pubNsec to set.
       * @return This builder for chaining.
       */
      public Builder setPubNsec(long value) {

        pubNsec_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 pub_nsec = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPubNsec() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pubNsec_ = 0L;
        onChanged();
        return this;
      }

      private long dataNsec_ ;
      /**
       * <code>uint64 data_nsec = 2;</code>
       * @return The dataNsec.
       */
      @java.lang.Override
      public long getDataNsec() {
        return dataNsec_;
      }
      /**
       * <code>uint64 data_nsec = 2;</code>
       * @param value The dataNsec to set.
       * @return This builder for chaining.
       */
      public Builder setDataNsec(long value) {

        dataNsec_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 data_nsec = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataNsec() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dataNsec_ = 0L;
        onChanged();
        return this;
      }

      private long seq_ ;
      /**
       * <code>uint64 seq = 3;</code>
       * @return The seq.
       */
      @java.lang.Override
      public long getSeq() {
        return seq_;
      }
      /**
       * <code>uint64 seq = 3;</code>
       * @param value The seq to set.
       * @return This builder for chaining.
       */
      public Builder setSeq(long value) {

        seq_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 seq = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeq() {
        bitField0_ = (bitField0_ & ~0x00000004);
        seq_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object frameId_ = "";
      /**
       * <code>string frame_id = 4;</code>
       * @return The frameId.
       */
      public java.lang.String getFrameId() {
        java.lang.Object ref = frameId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          frameId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string frame_id = 4;</code>
       * @return The bytes for frameId.
       */
      public com.google.protobuf.ByteString
          getFrameIdBytes() {
        java.lang.Object ref = frameId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          frameId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string frame_id = 4;</code>
       * @param value The frameId to set.
       * @return This builder for chaining.
       */
      public Builder setFrameId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        frameId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string frame_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrameId() {
        frameId_ = getDefaultInstance().getFrameId();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string frame_id = 4;</code>
       * @param value The bytes for frameId to set.
       * @return This builder for chaining.
       */
      public Builder setFrameIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        frameId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rbk.protocol.Message_Header)
    }

    // @@protoc_insertion_point(class_scope:rbk.protocol.Message_Header)
    private static final rbk.protocol.MessageHeader.Message_Header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rbk.protocol.MessageHeader.Message_Header();
    }

    public static rbk.protocol.MessageHeader.Message_Header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message_Header>
        PARSER = new com.google.protobuf.AbstractParser<Message_Header>() {
      @java.lang.Override
      public Message_Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message_Header> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message_Header> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rbk.protocol.MessageHeader.Message_Header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rbk_protocol_Message_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rbk_protocol_Message_Header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024message_header.proto\022\014rbk.protocol\"T\n\016" +
      "Message_Header\022\020\n\010pub_nsec\030\001 \001(\004\022\021\n\tdata" +
      "_nsec\030\002 \001(\004\022\013\n\003seq\030\003 \001(\004\022\020\n\010frame_id\030\004 \001" +
      "(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rbk_protocol_Message_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rbk_protocol_Message_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rbk_protocol_Message_Header_descriptor,
        new java.lang.String[] { "PubNsec", "DataNsec", "Seq", "FrameId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
