// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_ultrasonic.proto

package rbk.protocol;

public final class MessageUltrasonic {
  private MessageUltrasonic() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Message_UltraNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rbk.protocol.Message_UltraNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>double dist = 2;</code>
     * @return The dist.
     */
    double getDist();

    /**
     * <code>bool valid = 3;</code>
     * @return The valid.
     */
    boolean getValid();

    /**
     * <code>double pos_x = 4;</code>
     * @return The posX.
     */
    double getPosX();

    /**
     * <code>double pos_y = 5;</code>
     * @return The posY.
     */
    double getPosY();

    /**
     * <code>double pos_angle = 6;</code>
     * @return The posAngle.
     */
    double getPosAngle();

    /**
     * <code>double max_dist = 7;</code>
     * @return The maxDist.
     */
    double getMaxDist();

    /**
     * <code>double min_dist = 8;</code>
     * @return The minDist.
     */
    double getMinDist();

    /**
     * <code>double aperture = 9;</code>
     * @return The aperture.
     */
    double getAperture();

    /**
     * <code>bool forbidden = 10;</code>
     * @return The forbidden.
     */
    boolean getForbidden();

    /**
     * <code>.rbk.protocol.Message_Header header = 11;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.rbk.protocol.Message_Header header = 11;</code>
     * @return The header.
     */
    rbk.protocol.MessageHeader.Message_Header getHeader();
    /**
     * <code>.rbk.protocol.Message_Header header = 11;</code>
     */
    rbk.protocol.MessageHeader.Message_HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>int32 offset_time_ms = 12;</code>
     * @return The offsetTimeMs.
     */
    int getOffsetTimeMs();

    /**
     * <code>double pos_z = 13;</code>
     * @return The posZ.
     */
    double getPosZ();
  }
  /**
   * Protobuf type {@code rbk.protocol.Message_UltraNode}
   */
  public static final class Message_UltraNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rbk.protocol.Message_UltraNode)
      Message_UltraNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message_UltraNode.newBuilder() to construct.
    private Message_UltraNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message_UltraNode() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message_UltraNode();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rbk.protocol.MessageUltrasonic.internal_static_rbk_protocol_Message_UltraNode_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rbk.protocol.MessageUltrasonic.internal_static_rbk_protocol_Message_UltraNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rbk.protocol.MessageUltrasonic.Message_UltraNode.class, rbk.protocol.MessageUltrasonic.Message_UltraNode.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int DIST_FIELD_NUMBER = 2;
    private double dist_ = 0D;
    /**
     * <code>double dist = 2;</code>
     * @return The dist.
     */
    @java.lang.Override
    public double getDist() {
      return dist_;
    }

    public static final int VALID_FIELD_NUMBER = 3;
    private boolean valid_ = false;
    /**
     * <code>bool valid = 3;</code>
     * @return The valid.
     */
    @java.lang.Override
    public boolean getValid() {
      return valid_;
    }

    public static final int POS_X_FIELD_NUMBER = 4;
    private double posX_ = 0D;
    /**
     * <code>double pos_x = 4;</code>
     * @return The posX.
     */
    @java.lang.Override
    public double getPosX() {
      return posX_;
    }

    public static final int POS_Y_FIELD_NUMBER = 5;
    private double posY_ = 0D;
    /**
     * <code>double pos_y = 5;</code>
     * @return The posY.
     */
    @java.lang.Override
    public double getPosY() {
      return posY_;
    }

    public static final int POS_ANGLE_FIELD_NUMBER = 6;
    private double posAngle_ = 0D;
    /**
     * <code>double pos_angle = 6;</code>
     * @return The posAngle.
     */
    @java.lang.Override
    public double getPosAngle() {
      return posAngle_;
    }

    public static final int MAX_DIST_FIELD_NUMBER = 7;
    private double maxDist_ = 0D;
    /**
     * <code>double max_dist = 7;</code>
     * @return The maxDist.
     */
    @java.lang.Override
    public double getMaxDist() {
      return maxDist_;
    }

    public static final int MIN_DIST_FIELD_NUMBER = 8;
    private double minDist_ = 0D;
    /**
     * <code>double min_dist = 8;</code>
     * @return The minDist.
     */
    @java.lang.Override
    public double getMinDist() {
      return minDist_;
    }

    public static final int APERTURE_FIELD_NUMBER = 9;
    private double aperture_ = 0D;
    /**
     * <code>double aperture = 9;</code>
     * @return The aperture.
     */
    @java.lang.Override
    public double getAperture() {
      return aperture_;
    }

    public static final int FORBIDDEN_FIELD_NUMBER = 10;
    private boolean forbidden_ = false;
    /**
     * <code>bool forbidden = 10;</code>
     * @return The forbidden.
     */
    @java.lang.Override
    public boolean getForbidden() {
      return forbidden_;
    }

    public static final int HEADER_FIELD_NUMBER = 11;
    private rbk.protocol.MessageHeader.Message_Header header_;
    /**
     * <code>.rbk.protocol.Message_Header header = 11;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.rbk.protocol.Message_Header header = 11;</code>
     * @return The header.
     */
    @java.lang.Override
    public rbk.protocol.MessageHeader.Message_Header getHeader() {
      return header_ == null ? rbk.protocol.MessageHeader.Message_Header.getDefaultInstance() : header_;
    }
    /**
     * <code>.rbk.protocol.Message_Header header = 11;</code>
     */
    @java.lang.Override
    public rbk.protocol.MessageHeader.Message_HeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? rbk.protocol.MessageHeader.Message_Header.getDefaultInstance() : header_;
    }

    public static final int OFFSET_TIME_MS_FIELD_NUMBER = 12;
    private int offsetTimeMs_ = 0;
    /**
     * <code>int32 offset_time_ms = 12;</code>
     * @return The offsetTimeMs.
     */
    @java.lang.Override
    public int getOffsetTimeMs() {
      return offsetTimeMs_;
    }

    public static final int POS_Z_FIELD_NUMBER = 13;
    private double posZ_ = 0D;
    /**
     * <code>double pos_z = 13;</code>
     * @return The posZ.
     */
    @java.lang.Override
    public double getPosZ() {
      return posZ_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (java.lang.Double.doubleToRawLongBits(dist_) != 0) {
        output.writeDouble(2, dist_);
      }
      if (valid_ != false) {
        output.writeBool(3, valid_);
      }
      if (java.lang.Double.doubleToRawLongBits(posX_) != 0) {
        output.writeDouble(4, posX_);
      }
      if (java.lang.Double.doubleToRawLongBits(posY_) != 0) {
        output.writeDouble(5, posY_);
      }
      if (java.lang.Double.doubleToRawLongBits(posAngle_) != 0) {
        output.writeDouble(6, posAngle_);
      }
      if (java.lang.Double.doubleToRawLongBits(maxDist_) != 0) {
        output.writeDouble(7, maxDist_);
      }
      if (java.lang.Double.doubleToRawLongBits(minDist_) != 0) {
        output.writeDouble(8, minDist_);
      }
      if (java.lang.Double.doubleToRawLongBits(aperture_) != 0) {
        output.writeDouble(9, aperture_);
      }
      if (forbidden_ != false) {
        output.writeBool(10, forbidden_);
      }
      if (header_ != null) {
        output.writeMessage(11, getHeader());
      }
      if (offsetTimeMs_ != 0) {
        output.writeInt32(12, offsetTimeMs_);
      }
      if (java.lang.Double.doubleToRawLongBits(posZ_) != 0) {
        output.writeDouble(13, posZ_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (java.lang.Double.doubleToRawLongBits(dist_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, dist_);
      }
      if (valid_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, valid_);
      }
      if (java.lang.Double.doubleToRawLongBits(posX_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, posX_);
      }
      if (java.lang.Double.doubleToRawLongBits(posY_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, posY_);
      }
      if (java.lang.Double.doubleToRawLongBits(posAngle_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, posAngle_);
      }
      if (java.lang.Double.doubleToRawLongBits(maxDist_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, maxDist_);
      }
      if (java.lang.Double.doubleToRawLongBits(minDist_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, minDist_);
      }
      if (java.lang.Double.doubleToRawLongBits(aperture_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, aperture_);
      }
      if (forbidden_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, forbidden_);
      }
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getHeader());
      }
      if (offsetTimeMs_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, offsetTimeMs_);
      }
      if (java.lang.Double.doubleToRawLongBits(posZ_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(13, posZ_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rbk.protocol.MessageUltrasonic.Message_UltraNode)) {
        return super.equals(obj);
      }
      rbk.protocol.MessageUltrasonic.Message_UltraNode other = (rbk.protocol.MessageUltrasonic.Message_UltraNode) obj;

      if (getId()
          != other.getId()) return false;
      if (java.lang.Double.doubleToLongBits(getDist())
          != java.lang.Double.doubleToLongBits(
              other.getDist())) return false;
      if (getValid()
          != other.getValid()) return false;
      if (java.lang.Double.doubleToLongBits(getPosX())
          != java.lang.Double.doubleToLongBits(
              other.getPosX())) return false;
      if (java.lang.Double.doubleToLongBits(getPosY())
          != java.lang.Double.doubleToLongBits(
              other.getPosY())) return false;
      if (java.lang.Double.doubleToLongBits(getPosAngle())
          != java.lang.Double.doubleToLongBits(
              other.getPosAngle())) return false;
      if (java.lang.Double.doubleToLongBits(getMaxDist())
          != java.lang.Double.doubleToLongBits(
              other.getMaxDist())) return false;
      if (java.lang.Double.doubleToLongBits(getMinDist())
          != java.lang.Double.doubleToLongBits(
              other.getMinDist())) return false;
      if (java.lang.Double.doubleToLongBits(getAperture())
          != java.lang.Double.doubleToLongBits(
              other.getAperture())) return false;
      if (getForbidden()
          != other.getForbidden()) return false;
      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (getOffsetTimeMs()
          != other.getOffsetTimeMs()) return false;
      if (java.lang.Double.doubleToLongBits(getPosZ())
          != java.lang.Double.doubleToLongBits(
              other.getPosZ())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + DIST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDist()));
      hash = (37 * hash) + VALID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getValid());
      hash = (37 * hash) + POS_X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPosX()));
      hash = (37 * hash) + POS_Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPosY()));
      hash = (37 * hash) + POS_ANGLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPosAngle()));
      hash = (37 * hash) + MAX_DIST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMaxDist()));
      hash = (37 * hash) + MIN_DIST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMinDist()));
      hash = (37 * hash) + APERTURE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAperture()));
      hash = (37 * hash) + FORBIDDEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getForbidden());
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      hash = (37 * hash) + OFFSET_TIME_MS_FIELD_NUMBER;
      hash = (53 * hash) + getOffsetTimeMs();
      hash = (37 * hash) + POS_Z_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPosZ()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rbk.protocol.MessageUltrasonic.Message_UltraNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageUltrasonic.Message_UltraNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageUltrasonic.Message_UltraNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageUltrasonic.Message_UltraNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageUltrasonic.Message_UltraNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageUltrasonic.Message_UltraNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageUltrasonic.Message_UltraNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.MessageUltrasonic.Message_UltraNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static rbk.protocol.MessageUltrasonic.Message_UltraNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static rbk.protocol.MessageUltrasonic.Message_UltraNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rbk.protocol.MessageUltrasonic.Message_UltraNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.MessageUltrasonic.Message_UltraNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rbk.protocol.MessageUltrasonic.Message_UltraNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rbk.protocol.Message_UltraNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rbk.protocol.Message_UltraNode)
        rbk.protocol.MessageUltrasonic.Message_UltraNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rbk.protocol.MessageUltrasonic.internal_static_rbk_protocol_Message_UltraNode_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rbk.protocol.MessageUltrasonic.internal_static_rbk_protocol_Message_UltraNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rbk.protocol.MessageUltrasonic.Message_UltraNode.class, rbk.protocol.MessageUltrasonic.Message_UltraNode.Builder.class);
      }

      // Construct using rbk.protocol.MessageUltrasonic.Message_UltraNode.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        dist_ = 0D;
        valid_ = false;
        posX_ = 0D;
        posY_ = 0D;
        posAngle_ = 0D;
        maxDist_ = 0D;
        minDist_ = 0D;
        aperture_ = 0D;
        forbidden_ = false;
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        offsetTimeMs_ = 0;
        posZ_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rbk.protocol.MessageUltrasonic.internal_static_rbk_protocol_Message_UltraNode_descriptor;
      }

      @java.lang.Override
      public rbk.protocol.MessageUltrasonic.Message_UltraNode getDefaultInstanceForType() {
        return rbk.protocol.MessageUltrasonic.Message_UltraNode.getDefaultInstance();
      }

      @java.lang.Override
      public rbk.protocol.MessageUltrasonic.Message_UltraNode build() {
        rbk.protocol.MessageUltrasonic.Message_UltraNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rbk.protocol.MessageUltrasonic.Message_UltraNode buildPartial() {
        rbk.protocol.MessageUltrasonic.Message_UltraNode result = new rbk.protocol.MessageUltrasonic.Message_UltraNode(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(rbk.protocol.MessageUltrasonic.Message_UltraNode result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.dist_ = dist_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.valid_ = valid_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.posX_ = posX_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.posY_ = posY_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.posAngle_ = posAngle_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.maxDist_ = maxDist_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.minDist_ = minDist_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.aperture_ = aperture_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.forbidden_ = forbidden_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.header_ = headerBuilder_ == null
              ? header_
              : headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.offsetTimeMs_ = offsetTimeMs_;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.posZ_ = posZ_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rbk.protocol.MessageUltrasonic.Message_UltraNode) {
          return mergeFrom((rbk.protocol.MessageUltrasonic.Message_UltraNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rbk.protocol.MessageUltrasonic.Message_UltraNode other) {
        if (other == rbk.protocol.MessageUltrasonic.Message_UltraNode.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getDist() != 0D) {
          setDist(other.getDist());
        }
        if (other.getValid() != false) {
          setValid(other.getValid());
        }
        if (other.getPosX() != 0D) {
          setPosX(other.getPosX());
        }
        if (other.getPosY() != 0D) {
          setPosY(other.getPosY());
        }
        if (other.getPosAngle() != 0D) {
          setPosAngle(other.getPosAngle());
        }
        if (other.getMaxDist() != 0D) {
          setMaxDist(other.getMaxDist());
        }
        if (other.getMinDist() != 0D) {
          setMinDist(other.getMinDist());
        }
        if (other.getAperture() != 0D) {
          setAperture(other.getAperture());
        }
        if (other.getForbidden() != false) {
          setForbidden(other.getForbidden());
        }
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.getOffsetTimeMs() != 0) {
          setOffsetTimeMs(other.getOffsetTimeMs());
        }
        if (other.getPosZ() != 0D) {
          setPosZ(other.getPosZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 17: {
                dist_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 24: {
                valid_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 33: {
                posX_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 41: {
                posY_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              case 49: {
                posAngle_ = input.readDouble();
                bitField0_ |= 0x00000020;
                break;
              } // case 49
              case 57: {
                maxDist_ = input.readDouble();
                bitField0_ |= 0x00000040;
                break;
              } // case 57
              case 65: {
                minDist_ = input.readDouble();
                bitField0_ |= 0x00000080;
                break;
              } // case 65
              case 73: {
                aperture_ = input.readDouble();
                bitField0_ |= 0x00000100;
                break;
              } // case 73
              case 80: {
                forbidden_ = input.readBool();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              case 90: {
                input.readMessage(
                    getHeaderFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000400;
                break;
              } // case 90
              case 96: {
                offsetTimeMs_ = input.readInt32();
                bitField0_ |= 0x00000800;
                break;
              } // case 96
              case 105: {
                posZ_ = input.readDouble();
                bitField0_ |= 0x00001000;
                break;
              } // case 105
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private double dist_ ;
      /**
       * <code>double dist = 2;</code>
       * @return The dist.
       */
      @java.lang.Override
      public double getDist() {
        return dist_;
      }
      /**
       * <code>double dist = 2;</code>
       * @param value The dist to set.
       * @return This builder for chaining.
       */
      public Builder setDist(double value) {

        dist_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double dist = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDist() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dist_ = 0D;
        onChanged();
        return this;
      }

      private boolean valid_ ;
      /**
       * <code>bool valid = 3;</code>
       * @return The valid.
       */
      @java.lang.Override
      public boolean getValid() {
        return valid_;
      }
      /**
       * <code>bool valid = 3;</code>
       * @param value The valid to set.
       * @return This builder for chaining.
       */
      public Builder setValid(boolean value) {

        valid_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool valid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        valid_ = false;
        onChanged();
        return this;
      }

      private double posX_ ;
      /**
       * <code>double pos_x = 4;</code>
       * @return The posX.
       */
      @java.lang.Override
      public double getPosX() {
        return posX_;
      }
      /**
       * <code>double pos_x = 4;</code>
       * @param value The posX to set.
       * @return This builder for chaining.
       */
      public Builder setPosX(double value) {

        posX_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double pos_x = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosX() {
        bitField0_ = (bitField0_ & ~0x00000008);
        posX_ = 0D;
        onChanged();
        return this;
      }

      private double posY_ ;
      /**
       * <code>double pos_y = 5;</code>
       * @return The posY.
       */
      @java.lang.Override
      public double getPosY() {
        return posY_;
      }
      /**
       * <code>double pos_y = 5;</code>
       * @param value The posY to set.
       * @return This builder for chaining.
       */
      public Builder setPosY(double value) {

        posY_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>double pos_y = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosY() {
        bitField0_ = (bitField0_ & ~0x00000010);
        posY_ = 0D;
        onChanged();
        return this;
      }

      private double posAngle_ ;
      /**
       * <code>double pos_angle = 6;</code>
       * @return The posAngle.
       */
      @java.lang.Override
      public double getPosAngle() {
        return posAngle_;
      }
      /**
       * <code>double pos_angle = 6;</code>
       * @param value The posAngle to set.
       * @return This builder for chaining.
       */
      public Builder setPosAngle(double value) {

        posAngle_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>double pos_angle = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosAngle() {
        bitField0_ = (bitField0_ & ~0x00000020);
        posAngle_ = 0D;
        onChanged();
        return this;
      }

      private double maxDist_ ;
      /**
       * <code>double max_dist = 7;</code>
       * @return The maxDist.
       */
      @java.lang.Override
      public double getMaxDist() {
        return maxDist_;
      }
      /**
       * <code>double max_dist = 7;</code>
       * @param value The maxDist to set.
       * @return This builder for chaining.
       */
      public Builder setMaxDist(double value) {

        maxDist_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>double max_dist = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxDist() {
        bitField0_ = (bitField0_ & ~0x00000040);
        maxDist_ = 0D;
        onChanged();
        return this;
      }

      private double minDist_ ;
      /**
       * <code>double min_dist = 8;</code>
       * @return The minDist.
       */
      @java.lang.Override
      public double getMinDist() {
        return minDist_;
      }
      /**
       * <code>double min_dist = 8;</code>
       * @param value The minDist to set.
       * @return This builder for chaining.
       */
      public Builder setMinDist(double value) {

        minDist_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>double min_dist = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinDist() {
        bitField0_ = (bitField0_ & ~0x00000080);
        minDist_ = 0D;
        onChanged();
        return this;
      }

      private double aperture_ ;
      /**
       * <code>double aperture = 9;</code>
       * @return The aperture.
       */
      @java.lang.Override
      public double getAperture() {
        return aperture_;
      }
      /**
       * <code>double aperture = 9;</code>
       * @param value The aperture to set.
       * @return This builder for chaining.
       */
      public Builder setAperture(double value) {

        aperture_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>double aperture = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearAperture() {
        bitField0_ = (bitField0_ & ~0x00000100);
        aperture_ = 0D;
        onChanged();
        return this;
      }

      private boolean forbidden_ ;
      /**
       * <code>bool forbidden = 10;</code>
       * @return The forbidden.
       */
      @java.lang.Override
      public boolean getForbidden() {
        return forbidden_;
      }
      /**
       * <code>bool forbidden = 10;</code>
       * @param value The forbidden to set.
       * @return This builder for chaining.
       */
      public Builder setForbidden(boolean value) {

        forbidden_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>bool forbidden = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearForbidden() {
        bitField0_ = (bitField0_ & ~0x00000200);
        forbidden_ = false;
        onChanged();
        return this;
      }

      private rbk.protocol.MessageHeader.Message_Header header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          rbk.protocol.MessageHeader.Message_Header, rbk.protocol.MessageHeader.Message_Header.Builder, rbk.protocol.MessageHeader.Message_HeaderOrBuilder> headerBuilder_;
      /**
       * <code>.rbk.protocol.Message_Header header = 11;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>.rbk.protocol.Message_Header header = 11;</code>
       * @return The header.
       */
      public rbk.protocol.MessageHeader.Message_Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? rbk.protocol.MessageHeader.Message_Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.rbk.protocol.Message_Header header = 11;</code>
       */
      public Builder setHeader(rbk.protocol.MessageHeader.Message_Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>.rbk.protocol.Message_Header header = 11;</code>
       */
      public Builder setHeader(
          rbk.protocol.MessageHeader.Message_Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>.rbk.protocol.Message_Header header = 11;</code>
       */
      public Builder mergeHeader(rbk.protocol.MessageHeader.Message_Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000400) != 0) &&
            header_ != null &&
            header_ != rbk.protocol.MessageHeader.Message_Header.getDefaultInstance()) {
            getHeaderBuilder().mergeFrom(value);
          } else {
            header_ = value;
          }
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>.rbk.protocol.Message_Header header = 11;</code>
       */
      public Builder clearHeader() {
        bitField0_ = (bitField0_ & ~0x00000400);
        header_ = null;
        if (headerBuilder_ != null) {
          headerBuilder_.dispose();
          headerBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.rbk.protocol.Message_Header header = 11;</code>
       */
      public rbk.protocol.MessageHeader.Message_Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000400;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.rbk.protocol.Message_Header header = 11;</code>
       */
      public rbk.protocol.MessageHeader.Message_HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              rbk.protocol.MessageHeader.Message_Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.rbk.protocol.Message_Header header = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          rbk.protocol.MessageHeader.Message_Header, rbk.protocol.MessageHeader.Message_Header.Builder, rbk.protocol.MessageHeader.Message_HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              rbk.protocol.MessageHeader.Message_Header, rbk.protocol.MessageHeader.Message_Header.Builder, rbk.protocol.MessageHeader.Message_HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private int offsetTimeMs_ ;
      /**
       * <code>int32 offset_time_ms = 12;</code>
       * @return The offsetTimeMs.
       */
      @java.lang.Override
      public int getOffsetTimeMs() {
        return offsetTimeMs_;
      }
      /**
       * <code>int32 offset_time_ms = 12;</code>
       * @param value The offsetTimeMs to set.
       * @return This builder for chaining.
       */
      public Builder setOffsetTimeMs(int value) {

        offsetTimeMs_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>int32 offset_time_ms = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffsetTimeMs() {
        bitField0_ = (bitField0_ & ~0x00000800);
        offsetTimeMs_ = 0;
        onChanged();
        return this;
      }

      private double posZ_ ;
      /**
       * <code>double pos_z = 13;</code>
       * @return The posZ.
       */
      @java.lang.Override
      public double getPosZ() {
        return posZ_;
      }
      /**
       * <code>double pos_z = 13;</code>
       * @param value The posZ to set.
       * @return This builder for chaining.
       */
      public Builder setPosZ(double value) {

        posZ_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <code>double pos_z = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosZ() {
        bitField0_ = (bitField0_ & ~0x00001000);
        posZ_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rbk.protocol.Message_UltraNode)
    }

    // @@protoc_insertion_point(class_scope:rbk.protocol.Message_UltraNode)
    private static final rbk.protocol.MessageUltrasonic.Message_UltraNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rbk.protocol.MessageUltrasonic.Message_UltraNode();
    }

    public static rbk.protocol.MessageUltrasonic.Message_UltraNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message_UltraNode>
        PARSER = new com.google.protobuf.AbstractParser<Message_UltraNode>() {
      @java.lang.Override
      public Message_UltraNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message_UltraNode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message_UltraNode> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rbk.protocol.MessageUltrasonic.Message_UltraNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Message_UltrasonicOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rbk.protocol.Message_Ultrasonic)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 cycle = 1;</code>
     * @return The cycle.
     */
    int getCycle();

    /**
     * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
     */
    java.util.List<rbk.protocol.MessageUltrasonic.Message_UltraNode> 
        getNodesList();
    /**
     * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
     */
    rbk.protocol.MessageUltrasonic.Message_UltraNode getNodes(int index);
    /**
     * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
     */
    int getNodesCount();
    /**
     * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
     */
    java.util.List<? extends rbk.protocol.MessageUltrasonic.Message_UltraNodeOrBuilder> 
        getNodesOrBuilderList();
    /**
     * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
     */
    rbk.protocol.MessageUltrasonic.Message_UltraNodeOrBuilder getNodesOrBuilder(
        int index);

    /**
     * <code>uint64 base_time_ns = 3;</code>
     * @return The baseTimeNs.
     */
    long getBaseTimeNs();
  }
  /**
   * Protobuf type {@code rbk.protocol.Message_Ultrasonic}
   */
  public static final class Message_Ultrasonic extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rbk.protocol.Message_Ultrasonic)
      Message_UltrasonicOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message_Ultrasonic.newBuilder() to construct.
    private Message_Ultrasonic(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message_Ultrasonic() {
      nodes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message_Ultrasonic();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rbk.protocol.MessageUltrasonic.internal_static_rbk_protocol_Message_Ultrasonic_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rbk.protocol.MessageUltrasonic.internal_static_rbk_protocol_Message_Ultrasonic_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rbk.protocol.MessageUltrasonic.Message_Ultrasonic.class, rbk.protocol.MessageUltrasonic.Message_Ultrasonic.Builder.class);
    }

    public static final int CYCLE_FIELD_NUMBER = 1;
    private int cycle_ = 0;
    /**
     * <code>uint32 cycle = 1;</code>
     * @return The cycle.
     */
    @java.lang.Override
    public int getCycle() {
      return cycle_;
    }

    public static final int NODES_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<rbk.protocol.MessageUltrasonic.Message_UltraNode> nodes_;
    /**
     * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
     */
    @java.lang.Override
    public java.util.List<rbk.protocol.MessageUltrasonic.Message_UltraNode> getNodesList() {
      return nodes_;
    }
    /**
     * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends rbk.protocol.MessageUltrasonic.Message_UltraNodeOrBuilder> 
        getNodesOrBuilderList() {
      return nodes_;
    }
    /**
     * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
     */
    @java.lang.Override
    public int getNodesCount() {
      return nodes_.size();
    }
    /**
     * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
     */
    @java.lang.Override
    public rbk.protocol.MessageUltrasonic.Message_UltraNode getNodes(int index) {
      return nodes_.get(index);
    }
    /**
     * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
     */
    @java.lang.Override
    public rbk.protocol.MessageUltrasonic.Message_UltraNodeOrBuilder getNodesOrBuilder(
        int index) {
      return nodes_.get(index);
    }

    public static final int BASE_TIME_NS_FIELD_NUMBER = 3;
    private long baseTimeNs_ = 0L;
    /**
     * <code>uint64 base_time_ns = 3;</code>
     * @return The baseTimeNs.
     */
    @java.lang.Override
    public long getBaseTimeNs() {
      return baseTimeNs_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cycle_ != 0) {
        output.writeUInt32(1, cycle_);
      }
      for (int i = 0; i < nodes_.size(); i++) {
        output.writeMessage(2, nodes_.get(i));
      }
      if (baseTimeNs_ != 0L) {
        output.writeUInt64(3, baseTimeNs_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cycle_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, cycle_);
      }
      for (int i = 0; i < nodes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, nodes_.get(i));
      }
      if (baseTimeNs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, baseTimeNs_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rbk.protocol.MessageUltrasonic.Message_Ultrasonic)) {
        return super.equals(obj);
      }
      rbk.protocol.MessageUltrasonic.Message_Ultrasonic other = (rbk.protocol.MessageUltrasonic.Message_Ultrasonic) obj;

      if (getCycle()
          != other.getCycle()) return false;
      if (!getNodesList()
          .equals(other.getNodesList())) return false;
      if (getBaseTimeNs()
          != other.getBaseTimeNs()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CYCLE_FIELD_NUMBER;
      hash = (53 * hash) + getCycle();
      if (getNodesCount() > 0) {
        hash = (37 * hash) + NODES_FIELD_NUMBER;
        hash = (53 * hash) + getNodesList().hashCode();
      }
      hash = (37 * hash) + BASE_TIME_NS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBaseTimeNs());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rbk.protocol.MessageUltrasonic.Message_Ultrasonic parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageUltrasonic.Message_Ultrasonic parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageUltrasonic.Message_Ultrasonic parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageUltrasonic.Message_Ultrasonic parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageUltrasonic.Message_Ultrasonic parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.MessageUltrasonic.Message_Ultrasonic parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.MessageUltrasonic.Message_Ultrasonic parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.MessageUltrasonic.Message_Ultrasonic parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static rbk.protocol.MessageUltrasonic.Message_Ultrasonic parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static rbk.protocol.MessageUltrasonic.Message_Ultrasonic parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rbk.protocol.MessageUltrasonic.Message_Ultrasonic parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.MessageUltrasonic.Message_Ultrasonic parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rbk.protocol.MessageUltrasonic.Message_Ultrasonic prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rbk.protocol.Message_Ultrasonic}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rbk.protocol.Message_Ultrasonic)
        rbk.protocol.MessageUltrasonic.Message_UltrasonicOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rbk.protocol.MessageUltrasonic.internal_static_rbk_protocol_Message_Ultrasonic_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rbk.protocol.MessageUltrasonic.internal_static_rbk_protocol_Message_Ultrasonic_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rbk.protocol.MessageUltrasonic.Message_Ultrasonic.class, rbk.protocol.MessageUltrasonic.Message_Ultrasonic.Builder.class);
      }

      // Construct using rbk.protocol.MessageUltrasonic.Message_Ultrasonic.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cycle_ = 0;
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
        } else {
          nodes_ = null;
          nodesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        baseTimeNs_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rbk.protocol.MessageUltrasonic.internal_static_rbk_protocol_Message_Ultrasonic_descriptor;
      }

      @java.lang.Override
      public rbk.protocol.MessageUltrasonic.Message_Ultrasonic getDefaultInstanceForType() {
        return rbk.protocol.MessageUltrasonic.Message_Ultrasonic.getDefaultInstance();
      }

      @java.lang.Override
      public rbk.protocol.MessageUltrasonic.Message_Ultrasonic build() {
        rbk.protocol.MessageUltrasonic.Message_Ultrasonic result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rbk.protocol.MessageUltrasonic.Message_Ultrasonic buildPartial() {
        rbk.protocol.MessageUltrasonic.Message_Ultrasonic result = new rbk.protocol.MessageUltrasonic.Message_Ultrasonic(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(rbk.protocol.MessageUltrasonic.Message_Ultrasonic result) {
        if (nodesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            nodes_ = java.util.Collections.unmodifiableList(nodes_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.nodes_ = nodes_;
        } else {
          result.nodes_ = nodesBuilder_.build();
        }
      }

      private void buildPartial0(rbk.protocol.MessageUltrasonic.Message_Ultrasonic result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cycle_ = cycle_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.baseTimeNs_ = baseTimeNs_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rbk.protocol.MessageUltrasonic.Message_Ultrasonic) {
          return mergeFrom((rbk.protocol.MessageUltrasonic.Message_Ultrasonic)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rbk.protocol.MessageUltrasonic.Message_Ultrasonic other) {
        if (other == rbk.protocol.MessageUltrasonic.Message_Ultrasonic.getDefaultInstance()) return this;
        if (other.getCycle() != 0) {
          setCycle(other.getCycle());
        }
        if (nodesBuilder_ == null) {
          if (!other.nodes_.isEmpty()) {
            if (nodes_.isEmpty()) {
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureNodesIsMutable();
              nodes_.addAll(other.nodes_);
            }
            onChanged();
          }
        } else {
          if (!other.nodes_.isEmpty()) {
            if (nodesBuilder_.isEmpty()) {
              nodesBuilder_.dispose();
              nodesBuilder_ = null;
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000002);
              nodesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodesFieldBuilder() : null;
            } else {
              nodesBuilder_.addAllMessages(other.nodes_);
            }
          }
        }
        if (other.getBaseTimeNs() != 0L) {
          setBaseTimeNs(other.getBaseTimeNs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                cycle_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                rbk.protocol.MessageUltrasonic.Message_UltraNode m =
                    input.readMessage(
                        rbk.protocol.MessageUltrasonic.Message_UltraNode.parser(),
                        extensionRegistry);
                if (nodesBuilder_ == null) {
                  ensureNodesIsMutable();
                  nodes_.add(m);
                } else {
                  nodesBuilder_.addMessage(m);
                }
                break;
              } // case 18
              case 24: {
                baseTimeNs_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int cycle_ ;
      /**
       * <code>uint32 cycle = 1;</code>
       * @return The cycle.
       */
      @java.lang.Override
      public int getCycle() {
        return cycle_;
      }
      /**
       * <code>uint32 cycle = 1;</code>
       * @param value The cycle to set.
       * @return This builder for chaining.
       */
      public Builder setCycle(int value) {

        cycle_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 cycle = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCycle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cycle_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<rbk.protocol.MessageUltrasonic.Message_UltraNode> nodes_ =
        java.util.Collections.emptyList();
      private void ensureNodesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          nodes_ = new java.util.ArrayList<rbk.protocol.MessageUltrasonic.Message_UltraNode>(nodes_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          rbk.protocol.MessageUltrasonic.Message_UltraNode, rbk.protocol.MessageUltrasonic.Message_UltraNode.Builder, rbk.protocol.MessageUltrasonic.Message_UltraNodeOrBuilder> nodesBuilder_;

      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public java.util.List<rbk.protocol.MessageUltrasonic.Message_UltraNode> getNodesList() {
        if (nodesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodes_);
        } else {
          return nodesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public int getNodesCount() {
        if (nodesBuilder_ == null) {
          return nodes_.size();
        } else {
          return nodesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public rbk.protocol.MessageUltrasonic.Message_UltraNode getNodes(int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);
        } else {
          return nodesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public Builder setNodes(
          int index, rbk.protocol.MessageUltrasonic.Message_UltraNode value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.set(index, value);
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public Builder setNodes(
          int index, rbk.protocol.MessageUltrasonic.Message_UltraNode.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public Builder addNodes(rbk.protocol.MessageUltrasonic.Message_UltraNode value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public Builder addNodes(
          int index, rbk.protocol.MessageUltrasonic.Message_UltraNode value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(index, value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public Builder addNodes(
          rbk.protocol.MessageUltrasonic.Message_UltraNode.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public Builder addNodes(
          int index, rbk.protocol.MessageUltrasonic.Message_UltraNode.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public Builder addAllNodes(
          java.lang.Iterable<? extends rbk.protocol.MessageUltrasonic.Message_UltraNode> values) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodes_);
          onChanged();
        } else {
          nodesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public Builder clearNodes() {
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public Builder removeNodes(int index) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.remove(index);
          onChanged();
        } else {
          nodesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public rbk.protocol.MessageUltrasonic.Message_UltraNode.Builder getNodesBuilder(
          int index) {
        return getNodesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public rbk.protocol.MessageUltrasonic.Message_UltraNodeOrBuilder getNodesOrBuilder(
          int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);  } else {
          return nodesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public java.util.List<? extends rbk.protocol.MessageUltrasonic.Message_UltraNodeOrBuilder> 
           getNodesOrBuilderList() {
        if (nodesBuilder_ != null) {
          return nodesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodes_);
        }
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public rbk.protocol.MessageUltrasonic.Message_UltraNode.Builder addNodesBuilder() {
        return getNodesFieldBuilder().addBuilder(
            rbk.protocol.MessageUltrasonic.Message_UltraNode.getDefaultInstance());
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public rbk.protocol.MessageUltrasonic.Message_UltraNode.Builder addNodesBuilder(
          int index) {
        return getNodesFieldBuilder().addBuilder(
            index, rbk.protocol.MessageUltrasonic.Message_UltraNode.getDefaultInstance());
      }
      /**
       * <code>repeated .rbk.protocol.Message_UltraNode nodes = 2;</code>
       */
      public java.util.List<rbk.protocol.MessageUltrasonic.Message_UltraNode.Builder> 
           getNodesBuilderList() {
        return getNodesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          rbk.protocol.MessageUltrasonic.Message_UltraNode, rbk.protocol.MessageUltrasonic.Message_UltraNode.Builder, rbk.protocol.MessageUltrasonic.Message_UltraNodeOrBuilder> 
          getNodesFieldBuilder() {
        if (nodesBuilder_ == null) {
          nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              rbk.protocol.MessageUltrasonic.Message_UltraNode, rbk.protocol.MessageUltrasonic.Message_UltraNode.Builder, rbk.protocol.MessageUltrasonic.Message_UltraNodeOrBuilder>(
                  nodes_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          nodes_ = null;
        }
        return nodesBuilder_;
      }

      private long baseTimeNs_ ;
      /**
       * <code>uint64 base_time_ns = 3;</code>
       * @return The baseTimeNs.
       */
      @java.lang.Override
      public long getBaseTimeNs() {
        return baseTimeNs_;
      }
      /**
       * <code>uint64 base_time_ns = 3;</code>
       * @param value The baseTimeNs to set.
       * @return This builder for chaining.
       */
      public Builder setBaseTimeNs(long value) {

        baseTimeNs_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 base_time_ns = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaseTimeNs() {
        bitField0_ = (bitField0_ & ~0x00000004);
        baseTimeNs_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rbk.protocol.Message_Ultrasonic)
    }

    // @@protoc_insertion_point(class_scope:rbk.protocol.Message_Ultrasonic)
    private static final rbk.protocol.MessageUltrasonic.Message_Ultrasonic DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rbk.protocol.MessageUltrasonic.Message_Ultrasonic();
    }

    public static rbk.protocol.MessageUltrasonic.Message_Ultrasonic getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message_Ultrasonic>
        PARSER = new com.google.protobuf.AbstractParser<Message_Ultrasonic>() {
      @java.lang.Override
      public Message_Ultrasonic parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message_Ultrasonic> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message_Ultrasonic> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rbk.protocol.MessageUltrasonic.Message_Ultrasonic getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rbk_protocol_Message_UltraNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rbk_protocol_Message_UltraNode_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rbk_protocol_Message_Ultrasonic_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rbk_protocol_Message_Ultrasonic_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030message_ultrasonic.proto\022\014rbk.protocol" +
      "\032\024message_header.proto\"\213\002\n\021Message_Ultra" +
      "Node\022\n\n\002id\030\001 \001(\005\022\014\n\004dist\030\002 \001(\001\022\r\n\005valid\030" +
      "\003 \001(\010\022\r\n\005pos_x\030\004 \001(\001\022\r\n\005pos_y\030\005 \001(\001\022\021\n\tp" +
      "os_angle\030\006 \001(\001\022\020\n\010max_dist\030\007 \001(\001\022\020\n\010min_" +
      "dist\030\010 \001(\001\022\020\n\010aperture\030\t \001(\001\022\021\n\tforbidde" +
      "n\030\n \001(\010\022,\n\006header\030\013 \001(\0132\034.rbk.protocol.M" +
      "essage_Header\022\026\n\016offset_time_ms\030\014 \001(\005\022\r\n" +
      "\005pos_z\030\r \001(\001\"i\n\022Message_Ultrasonic\022\r\n\005cy" +
      "cle\030\001 \001(\r\022.\n\005nodes\030\002 \003(\0132\037.rbk.protocol." +
      "Message_UltraNode\022\024\n\014base_time_ns\030\003 \001(\004b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          rbk.protocol.MessageHeader.getDescriptor(),
        });
    internal_static_rbk_protocol_Message_UltraNode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rbk_protocol_Message_UltraNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rbk_protocol_Message_UltraNode_descriptor,
        new java.lang.String[] { "Id", "Dist", "Valid", "PosX", "PosY", "PosAngle", "MaxDist", "MinDist", "Aperture", "Forbidden", "Header", "OffsetTimeMs", "PosZ", });
    internal_static_rbk_protocol_Message_Ultrasonic_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rbk_protocol_Message_Ultrasonic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rbk_protocol_Message_Ultrasonic_descriptor,
        new java.lang.String[] { "Cycle", "Nodes", "BaseTimeNs", });
    rbk.protocol.MessageHeader.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
