// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_rds_door_status.proto

package rbk.protocol.rds;

public final class MessageRdsDoorStatus {
  private MessageRdsDoorStatus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Message_DoorStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rbk.protocol.rds.Message_DoorStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *自动门名称：
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     *自动门名称：
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *自动门状态：0 = 关闭，1 = 打开，
     * </pre>
     *
     * <code>bool doorstatus = 2;</code>
     * @return The doorstatus.
     */
    boolean getDoorstatus();

    /**
     * <pre>
     *自动门到位信息：0 = 未到位，1 = 已到位(门上升到顶的时候，这个是已到位)
     * </pre>
     *
     * <code>bool doorinplace = 3;</code>
     * @return The doorinplace.
     */
    boolean getDoorinplace();

    /**
     * <pre>
     *自动门连接状态：0 = 未连接，1 = 已连接
     * </pre>
     *
     * <code>bool connection_status = 4;</code>
     * @return The connectionStatus.
     */
    boolean getConnectionStatus();

    /**
     * <pre>
     *电梯是否被人为禁用
     * </pre>
     *
     * <code>bool forbidden = 5;</code>
     * @return The forbidden.
     */
    boolean getForbidden();
  }
  /**
   * Protobuf type {@code rbk.protocol.rds.Message_DoorStatus}
   */
  public static final class Message_DoorStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rbk.protocol.rds.Message_DoorStatus)
      Message_DoorStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message_DoorStatus.newBuilder() to construct.
    private Message_DoorStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message_DoorStatus() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message_DoorStatus();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rbk.protocol.rds.MessageRdsDoorStatus.internal_static_rbk_protocol_rds_Message_DoorStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rbk.protocol.rds.MessageRdsDoorStatus.internal_static_rbk_protocol_rds_Message_DoorStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.class, rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <pre>
     *自动门名称：
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *自动门名称：
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOORSTATUS_FIELD_NUMBER = 2;
    private boolean doorstatus_ = false;
    /**
     * <pre>
     *自动门状态：0 = 关闭，1 = 打开，
     * </pre>
     *
     * <code>bool doorstatus = 2;</code>
     * @return The doorstatus.
     */
    @java.lang.Override
    public boolean getDoorstatus() {
      return doorstatus_;
    }

    public static final int DOORINPLACE_FIELD_NUMBER = 3;
    private boolean doorinplace_ = false;
    /**
     * <pre>
     *自动门到位信息：0 = 未到位，1 = 已到位(门上升到顶的时候，这个是已到位)
     * </pre>
     *
     * <code>bool doorinplace = 3;</code>
     * @return The doorinplace.
     */
    @java.lang.Override
    public boolean getDoorinplace() {
      return doorinplace_;
    }

    public static final int CONNECTION_STATUS_FIELD_NUMBER = 4;
    private boolean connectionStatus_ = false;
    /**
     * <pre>
     *自动门连接状态：0 = 未连接，1 = 已连接
     * </pre>
     *
     * <code>bool connection_status = 4;</code>
     * @return The connectionStatus.
     */
    @java.lang.Override
    public boolean getConnectionStatus() {
      return connectionStatus_;
    }

    public static final int FORBIDDEN_FIELD_NUMBER = 5;
    private boolean forbidden_ = false;
    /**
     * <pre>
     *电梯是否被人为禁用
     * </pre>
     *
     * <code>bool forbidden = 5;</code>
     * @return The forbidden.
     */
    @java.lang.Override
    public boolean getForbidden() {
      return forbidden_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (doorstatus_ != false) {
        output.writeBool(2, doorstatus_);
      }
      if (doorinplace_ != false) {
        output.writeBool(3, doorinplace_);
      }
      if (connectionStatus_ != false) {
        output.writeBool(4, connectionStatus_);
      }
      if (forbidden_ != false) {
        output.writeBool(5, forbidden_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (doorstatus_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, doorstatus_);
      }
      if (doorinplace_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, doorinplace_);
      }
      if (connectionStatus_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, connectionStatus_);
      }
      if (forbidden_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, forbidden_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus)) {
        return super.equals(obj);
      }
      rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus other = (rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getDoorstatus()
          != other.getDoorstatus()) return false;
      if (getDoorinplace()
          != other.getDoorinplace()) return false;
      if (getConnectionStatus()
          != other.getConnectionStatus()) return false;
      if (getForbidden()
          != other.getForbidden()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DOORSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDoorstatus());
      hash = (37 * hash) + DOORINPLACE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDoorinplace());
      hash = (37 * hash) + CONNECTION_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getConnectionStatus());
      hash = (37 * hash) + FORBIDDEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getForbidden());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rbk.protocol.rds.Message_DoorStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rbk.protocol.rds.Message_DoorStatus)
        rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rbk.protocol.rds.MessageRdsDoorStatus.internal_static_rbk_protocol_rds_Message_DoorStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rbk.protocol.rds.MessageRdsDoorStatus.internal_static_rbk_protocol_rds_Message_DoorStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.class, rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.Builder.class);
      }

      // Construct using rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        doorstatus_ = false;
        doorinplace_ = false;
        connectionStatus_ = false;
        forbidden_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rbk.protocol.rds.MessageRdsDoorStatus.internal_static_rbk_protocol_rds_Message_DoorStatus_descriptor;
      }

      @java.lang.Override
      public rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus getDefaultInstanceForType() {
        return rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.getDefaultInstance();
      }

      @java.lang.Override
      public rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus build() {
        rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus buildPartial() {
        rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus result = new rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.doorstatus_ = doorstatus_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.doorinplace_ = doorinplace_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.connectionStatus_ = connectionStatus_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.forbidden_ = forbidden_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus) {
          return mergeFrom((rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus other) {
        if (other == rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getDoorstatus() != false) {
          setDoorstatus(other.getDoorstatus());
        }
        if (other.getDoorinplace() != false) {
          setDoorinplace(other.getDoorinplace());
        }
        if (other.getConnectionStatus() != false) {
          setConnectionStatus(other.getConnectionStatus());
        }
        if (other.getForbidden() != false) {
          setForbidden(other.getForbidden());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                doorstatus_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                doorinplace_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                connectionStatus_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                forbidden_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *自动门名称：
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *自动门名称：
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *自动门名称：
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *自动门名称：
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *自动门名称：
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private boolean doorstatus_ ;
      /**
       * <pre>
       *自动门状态：0 = 关闭，1 = 打开，
       * </pre>
       *
       * <code>bool doorstatus = 2;</code>
       * @return The doorstatus.
       */
      @java.lang.Override
      public boolean getDoorstatus() {
        return doorstatus_;
      }
      /**
       * <pre>
       *自动门状态：0 = 关闭，1 = 打开，
       * </pre>
       *
       * <code>bool doorstatus = 2;</code>
       * @param value The doorstatus to set.
       * @return This builder for chaining.
       */
      public Builder setDoorstatus(boolean value) {

        doorstatus_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *自动门状态：0 = 关闭，1 = 打开，
       * </pre>
       *
       * <code>bool doorstatus = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDoorstatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        doorstatus_ = false;
        onChanged();
        return this;
      }

      private boolean doorinplace_ ;
      /**
       * <pre>
       *自动门到位信息：0 = 未到位，1 = 已到位(门上升到顶的时候，这个是已到位)
       * </pre>
       *
       * <code>bool doorinplace = 3;</code>
       * @return The doorinplace.
       */
      @java.lang.Override
      public boolean getDoorinplace() {
        return doorinplace_;
      }
      /**
       * <pre>
       *自动门到位信息：0 = 未到位，1 = 已到位(门上升到顶的时候，这个是已到位)
       * </pre>
       *
       * <code>bool doorinplace = 3;</code>
       * @param value The doorinplace to set.
       * @return This builder for chaining.
       */
      public Builder setDoorinplace(boolean value) {

        doorinplace_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *自动门到位信息：0 = 未到位，1 = 已到位(门上升到顶的时候，这个是已到位)
       * </pre>
       *
       * <code>bool doorinplace = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDoorinplace() {
        bitField0_ = (bitField0_ & ~0x00000004);
        doorinplace_ = false;
        onChanged();
        return this;
      }

      private boolean connectionStatus_ ;
      /**
       * <pre>
       *自动门连接状态：0 = 未连接，1 = 已连接
       * </pre>
       *
       * <code>bool connection_status = 4;</code>
       * @return The connectionStatus.
       */
      @java.lang.Override
      public boolean getConnectionStatus() {
        return connectionStatus_;
      }
      /**
       * <pre>
       *自动门连接状态：0 = 未连接，1 = 已连接
       * </pre>
       *
       * <code>bool connection_status = 4;</code>
       * @param value The connectionStatus to set.
       * @return This builder for chaining.
       */
      public Builder setConnectionStatus(boolean value) {

        connectionStatus_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *自动门连接状态：0 = 未连接，1 = 已连接
       * </pre>
       *
       * <code>bool connection_status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnectionStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        connectionStatus_ = false;
        onChanged();
        return this;
      }

      private boolean forbidden_ ;
      /**
       * <pre>
       *电梯是否被人为禁用
       * </pre>
       *
       * <code>bool forbidden = 5;</code>
       * @return The forbidden.
       */
      @java.lang.Override
      public boolean getForbidden() {
        return forbidden_;
      }
      /**
       * <pre>
       *电梯是否被人为禁用
       * </pre>
       *
       * <code>bool forbidden = 5;</code>
       * @param value The forbidden to set.
       * @return This builder for chaining.
       */
      public Builder setForbidden(boolean value) {

        forbidden_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *电梯是否被人为禁用
       * </pre>
       *
       * <code>bool forbidden = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearForbidden() {
        bitField0_ = (bitField0_ & ~0x00000010);
        forbidden_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rbk.protocol.rds.Message_DoorStatus)
    }

    // @@protoc_insertion_point(class_scope:rbk.protocol.rds.Message_DoorStatus)
    private static final rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus();
    }

    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message_DoorStatus>
        PARSER = new com.google.protobuf.AbstractParser<Message_DoorStatus>() {
      @java.lang.Override
      public Message_DoorStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message_DoorStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message_DoorStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Message_DoorsStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rbk.protocol.rds.Message_DoorsStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
     */
    java.util.List<rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus> 
        getDoorsList();
    /**
     * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
     */
    rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus getDoors(int index);
    /**
     * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
     */
    int getDoorsCount();
    /**
     * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
     */
    java.util.List<? extends rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatusOrBuilder> 
        getDoorsOrBuilderList();
    /**
     * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
     */
    rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatusOrBuilder getDoorsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code rbk.protocol.rds.Message_DoorsStatus}
   */
  public static final class Message_DoorsStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rbk.protocol.rds.Message_DoorsStatus)
      Message_DoorsStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message_DoorsStatus.newBuilder() to construct.
    private Message_DoorsStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message_DoorsStatus() {
      doors_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message_DoorsStatus();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rbk.protocol.rds.MessageRdsDoorStatus.internal_static_rbk_protocol_rds_Message_DoorsStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rbk.protocol.rds.MessageRdsDoorStatus.internal_static_rbk_protocol_rds_Message_DoorsStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus.class, rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus.Builder.class);
    }

    public static final int DOORS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus> doors_;
    /**
     * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
     */
    @java.lang.Override
    public java.util.List<rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus> getDoorsList() {
      return doors_;
    }
    /**
     * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatusOrBuilder> 
        getDoorsOrBuilderList() {
      return doors_;
    }
    /**
     * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
     */
    @java.lang.Override
    public int getDoorsCount() {
      return doors_.size();
    }
    /**
     * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
     */
    @java.lang.Override
    public rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus getDoors(int index) {
      return doors_.get(index);
    }
    /**
     * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
     */
    @java.lang.Override
    public rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatusOrBuilder getDoorsOrBuilder(
        int index) {
      return doors_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < doors_.size(); i++) {
        output.writeMessage(1, doors_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < doors_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, doors_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus)) {
        return super.equals(obj);
      }
      rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus other = (rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus) obj;

      if (!getDoorsList()
          .equals(other.getDoorsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDoorsCount() > 0) {
        hash = (37 * hash) + DOORS_FIELD_NUMBER;
        hash = (53 * hash) + getDoorsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rbk.protocol.rds.Message_DoorsStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rbk.protocol.rds.Message_DoorsStatus)
        rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rbk.protocol.rds.MessageRdsDoorStatus.internal_static_rbk_protocol_rds_Message_DoorsStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rbk.protocol.rds.MessageRdsDoorStatus.internal_static_rbk_protocol_rds_Message_DoorsStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus.class, rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus.Builder.class);
      }

      // Construct using rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (doorsBuilder_ == null) {
          doors_ = java.util.Collections.emptyList();
        } else {
          doors_ = null;
          doorsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rbk.protocol.rds.MessageRdsDoorStatus.internal_static_rbk_protocol_rds_Message_DoorsStatus_descriptor;
      }

      @java.lang.Override
      public rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus getDefaultInstanceForType() {
        return rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus.getDefaultInstance();
      }

      @java.lang.Override
      public rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus build() {
        rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus buildPartial() {
        rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus result = new rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus result) {
        if (doorsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            doors_ = java.util.Collections.unmodifiableList(doors_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.doors_ = doors_;
        } else {
          result.doors_ = doorsBuilder_.build();
        }
      }

      private void buildPartial0(rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus) {
          return mergeFrom((rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus other) {
        if (other == rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus.getDefaultInstance()) return this;
        if (doorsBuilder_ == null) {
          if (!other.doors_.isEmpty()) {
            if (doors_.isEmpty()) {
              doors_ = other.doors_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDoorsIsMutable();
              doors_.addAll(other.doors_);
            }
            onChanged();
          }
        } else {
          if (!other.doors_.isEmpty()) {
            if (doorsBuilder_.isEmpty()) {
              doorsBuilder_.dispose();
              doorsBuilder_ = null;
              doors_ = other.doors_;
              bitField0_ = (bitField0_ & ~0x00000001);
              doorsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDoorsFieldBuilder() : null;
            } else {
              doorsBuilder_.addAllMessages(other.doors_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus m =
                    input.readMessage(
                        rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.parser(),
                        extensionRegistry);
                if (doorsBuilder_ == null) {
                  ensureDoorsIsMutable();
                  doors_.add(m);
                } else {
                  doorsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus> doors_ =
        java.util.Collections.emptyList();
      private void ensureDoorsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          doors_ = new java.util.ArrayList<rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus>(doors_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus, rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.Builder, rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatusOrBuilder> doorsBuilder_;

      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public java.util.List<rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus> getDoorsList() {
        if (doorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(doors_);
        } else {
          return doorsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public int getDoorsCount() {
        if (doorsBuilder_ == null) {
          return doors_.size();
        } else {
          return doorsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus getDoors(int index) {
        if (doorsBuilder_ == null) {
          return doors_.get(index);
        } else {
          return doorsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public Builder setDoors(
          int index, rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus value) {
        if (doorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDoorsIsMutable();
          doors_.set(index, value);
          onChanged();
        } else {
          doorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public Builder setDoors(
          int index, rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.Builder builderForValue) {
        if (doorsBuilder_ == null) {
          ensureDoorsIsMutable();
          doors_.set(index, builderForValue.build());
          onChanged();
        } else {
          doorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public Builder addDoors(rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus value) {
        if (doorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDoorsIsMutable();
          doors_.add(value);
          onChanged();
        } else {
          doorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public Builder addDoors(
          int index, rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus value) {
        if (doorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDoorsIsMutable();
          doors_.add(index, value);
          onChanged();
        } else {
          doorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public Builder addDoors(
          rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.Builder builderForValue) {
        if (doorsBuilder_ == null) {
          ensureDoorsIsMutable();
          doors_.add(builderForValue.build());
          onChanged();
        } else {
          doorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public Builder addDoors(
          int index, rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.Builder builderForValue) {
        if (doorsBuilder_ == null) {
          ensureDoorsIsMutable();
          doors_.add(index, builderForValue.build());
          onChanged();
        } else {
          doorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public Builder addAllDoors(
          java.lang.Iterable<? extends rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus> values) {
        if (doorsBuilder_ == null) {
          ensureDoorsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, doors_);
          onChanged();
        } else {
          doorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public Builder clearDoors() {
        if (doorsBuilder_ == null) {
          doors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          doorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public Builder removeDoors(int index) {
        if (doorsBuilder_ == null) {
          ensureDoorsIsMutable();
          doors_.remove(index);
          onChanged();
        } else {
          doorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.Builder getDoorsBuilder(
          int index) {
        return getDoorsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatusOrBuilder getDoorsOrBuilder(
          int index) {
        if (doorsBuilder_ == null) {
          return doors_.get(index);  } else {
          return doorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public java.util.List<? extends rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatusOrBuilder> 
           getDoorsOrBuilderList() {
        if (doorsBuilder_ != null) {
          return doorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(doors_);
        }
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.Builder addDoorsBuilder() {
        return getDoorsFieldBuilder().addBuilder(
            rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.Builder addDoorsBuilder(
          int index) {
        return getDoorsFieldBuilder().addBuilder(
            index, rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .rbk.protocol.rds.Message_DoorStatus doors = 1;</code>
       */
      public java.util.List<rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.Builder> 
           getDoorsBuilderList() {
        return getDoorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus, rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.Builder, rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatusOrBuilder> 
          getDoorsFieldBuilder() {
        if (doorsBuilder_ == null) {
          doorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus, rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatus.Builder, rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorStatusOrBuilder>(
                  doors_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          doors_ = null;
        }
        return doorsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rbk.protocol.rds.Message_DoorsStatus)
    }

    // @@protoc_insertion_point(class_scope:rbk.protocol.rds.Message_DoorsStatus)
    private static final rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus();
    }

    public static rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message_DoorsStatus>
        PARSER = new com.google.protobuf.AbstractParser<Message_DoorsStatus>() {
      @java.lang.Override
      public Message_DoorsStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message_DoorsStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message_DoorsStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public rbk.protocol.rds.MessageRdsDoorStatus.Message_DoorsStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rbk_protocol_rds_Message_DoorStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rbk_protocol_rds_Message_DoorStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rbk_protocol_rds_Message_DoorsStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rbk_protocol_rds_Message_DoorsStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035message_rds_door_status.proto\022\020rbk.pro" +
      "tocol.rds\"y\n\022Message_DoorStatus\022\014\n\004name\030" +
      "\001 \001(\t\022\022\n\ndoorstatus\030\002 \001(\010\022\023\n\013doorinplace" +
      "\030\003 \001(\010\022\031\n\021connection_status\030\004 \001(\010\022\021\n\tfor" +
      "bidden\030\005 \001(\010\"J\n\023Message_DoorsStatus\0223\n\005d" +
      "oors\030\001 \003(\0132$.rbk.protocol.rds.Message_Do" +
      "orStatusb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rbk_protocol_rds_Message_DoorStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rbk_protocol_rds_Message_DoorStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rbk_protocol_rds_Message_DoorStatus_descriptor,
        new java.lang.String[] { "Name", "Doorstatus", "Doorinplace", "ConnectionStatus", "Forbidden", });
    internal_static_rbk_protocol_rds_Message_DoorsStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rbk_protocol_rds_Message_DoorsStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rbk_protocol_rds_Message_DoorsStatus_descriptor,
        new java.lang.String[] { "Doors", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
